### ISSUE TITLE
Create Auto CNAME and A Records on DigitalOcean

### ISSUE THREAD

**Issue by fradducho** [pablokbs/peladonerd#10]
Hola, Excelente Canal de youtube y excelente trabajo el que haces.
*Tengo una pregunta sobre traefik.
Es posible que el traefik pueda crear automaticamente el record CNAME o A. del sub dominio?

y no tener que crearlo yo manualmente siempre en DigitalOcean u otro Controlador DNS o Dominio.?

No se si me he explicado.

Ejemplo: Dominio  minombre.com
Pero tengo un servicio que se llamara git.minombre.com

Es posible que  ya el traefik cree el record git.minombre.com en DigitalOcean sin tener yo que ir agregar el cname  directamente antes de deploy el docker-compose?

Muchas Gracias.

**Comment by pablokbs** [comment]
Gracias por los comentarios

Traefik en si no tiene esa funcionalidad, pero seguro podes hacer algun servicio que se conecte a la API de traefik y le pase el vhost y a su vez cree el registro en Digital Ocean (usando la API tambien) ... no es facil, pero todo es posible :)

**Comment by fradducho** [comment]
Muchas Gracias por la orientación  :)
