### ISSUE TITLE
Problemas con Poste.io

### ISSUE THREAD

**Issue by enmanuelrz** [pablokbs/peladonerd#104]
Hola, mil gracias por el tutorial para instalar Poste.io.

Lo instalé en un servidor de AWS y no podía enviar emails porque bloquean el puerto 25, así que recurrí a tu consejo de usar Sendgrid. Los correos se envían pero en Gmail llegan a la carpeta de promociones, el correo es para la empresa en dónde trabajo y sólo se usa para comunicaciones, no hacemos email-marketing. Probé con otros servicios  y al final me quedé con Amazon SES. En cada caso llega a la carpeta de promociones, en el último caso, llega a la carpeta de notificaciones. El dominio está validado tal y cómo lo exige Amazon SES para poder usarlo. Si alguien pudiera arrojarme una luz para que lleguen a la carpeta principal. Gracias.

**Comment by pablomenino** [comment]
Lo que podes hacer es mirar los headers del mail que te llega, y el código fuente, para ver si se le agrego algo (algún tag o alguna otra cosa en el medio), y que por esto Gamil lo tome como lo esta haciendo.

En mi caso uso Sendinblue, y le agregan al mail un tag de imagen HTML vacío, solo para ver si los mensajes llegan al destinatario.
