### ISSUE TITLE
Prometheus + Thanos

### ISSUE THREAD

**Issue by franrebo84** [pablokbs/peladonerd#106]
Hola Pelado! Muchas gracias por estos tutoriales, son super utiles.

Estoy probando este tutorial y me surgio una duda con respecto al primer paso:

```
kubectl --context cluster1 apply -f prometheus/setup
kubectl --context cluster1 apply -f prometheus/
```

De que repo sale el directorio con los yml de prometheus?  Asi busco las versiones mas nuevas del mismo, ya que tengo entendido que deprecaron una version de estos repos y hay una nueva version prometheus-community asi que estoy algo perdido con esto.

Gracias!

**Comment by pablokbs** [comment]
Buenas, salen de acá: https://github.com/prometheus-operator/kube-prometheus
