### ISSUE TITLE
Problema al conectarme al mail server desde aplicativo

### ISSUE THREAD

**Issue by cclozano** [pablokbs/peladonerd#107]
Hola Pablo y gente de la comunidad,
me he montado el contenedor de Poste.io, lo he desplegado con ansible, y el webmail va de maravilla,
sin embargo he tenido problemas al tratar de tratar de enviar correos desde una aplicacion que hice en java, 
se conecta y hace la autenticacion tanto por el puerto 25 como el 587, pero me devuelve el siguiente error:
```
DEBUG SMTP: got response code 550, with response: 550 Missing From header at envelope. Please fix email client settings or contact your system administrator.
DEBUG SMTP: MessagingException while sending, THROW: 
com.sun.mail.smtp.SMTPSendFailedException: 550 Missing From header at envelope. Please fix email client settings or contact your system administrator.
	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2267)
```
La configuracion que uso es la siguiente:
![image](https://user-images.githubusercontent.com/22644100/97525380-e33fd480-1963-11eb-8bea-823847c22225.png)

Adicional les dejo el script de ansible con el que despliego mi contenedor,
por favor, si me pueden ayudar se los agradeceria un mundo.

```---
- hosts: poste_server
  tasks:
    - name: Run Poste
      docker_container:
        name: poste2
        image: analogic/poste.io
        recreate: no
        state: started
        restart_policy: always
        env:
          HTTPS: 'ON'
          DISABLE_CLAMAV: 'TRUE'
        ports:
          - "25:25"
          - "80:80"
          - "443:443"
          - "110:110"
          - "143:143"
          - "465:465"
          - "587:587"
          - "993:993"
          - "995:995"
          - "4190:4190"
        networks:
          - name: host
        volumes:
          - "{{ansible_env.HOME}}/docker/volumes/poste/data:/data"
```

**Comment by pablokbs** [comment]
Pareciera que te falta el header `From` como te dice ahi
