### ISSUE TITLE
ValidationError(Deployment.spec): missing required field "selector" al aplicar kubernetes/9/02-hello-app-deployment.yaml

### ISSUE THREAD

**Issue by johannesanchez** [pablokbs/peladonerd#108]
Al aplicar manifiesto de deployment:

# kubectl apply -f 02-hello-app-deployment.yaml
error: error validating "02-hello-app-deployment.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by johannesanchez** [comment]
Falta incluir selector:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      role: hello
  template:
    metadata:
      labels:
        role: hello
    spec:
      containers:
      - name: hello
        image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"

**Comment by pablokbs** [comment]
Puedes hacer un PR con este cambio? Asi lo dejamos actualizado :)

**Comment by johannesanchez** [comment]
Hecho. Agregué el selector al 03-fluentd-daemonset.yaml que faltaba.
