### ISSUE TITLE
Problema con Nginx en RB Pi

### ISSUE THREAD

**Issue by Jnioms** [pablokbs/peladonerd#110]
Buenas tardes pelados! Segui el tutorial de "Nginx + SSL en Raspberry" y me encontre un problema.
Cuando entro a dominio.com, la pagina carga perfectamente y me hace la redireccion a https.
Cuando entro a www.dominio.com, me aparece el error 503 de nginx, supongo que por no tener configurado el /etc/nginx/conf.d/default.conf del nginx_proxy.
Encontre una solucion del estilo "dale no me gusta el video" que es corriendo el docker compose, copiando el /etc/nginx/conf.d/default.conf a la rbp, editandolo y agregando www.dominio.com al lado de dominio.com en las 2 lineas de server_name y copiandolo de vuelta al contenedor del nginx_proxy y metiendome con docker exec -it /bin/bash y corriendo nginx -s reload desde el contenedor.

El problema es que cuando tiro restart al compose o apago y vuelvo a arrancar la rbp, el /etc/nginx/conf.d/default.conf del contenedor del nginx_proxy vuelve a reescribirse y desaparece www.dominio.com, asi que no es una buena solucion.
Se les ocurre alguna manera en la que pueda hacer persistente el cambio?

**Comment by pablokbs** [comment]
Pasá tu config asi te podemos ayudar, pero probablemente lo unico que tengas que hacer es agregar `www.dominio.com` a tu lista de `VIRTUAL_HOST`

**Comment by Jnioms** [comment]
Gracias por contestar pela querido!
Copie y pegue el mismo yaml de compose que vos, y le agregue en la imagen del nginx el virtual host con `www.dominio.com` separado por coma al final. No se si deberia cambiar algo en el proxy tambien o solo con el nginx deberia tomarlo. Paso la configuracion del compose abajo:

`version: '3'

services:
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: duch/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx_fredrikson:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /home/pi/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=matehost.com.ar,www.matehost.com.ar
      - LETSENCRYPT_HOST=matehost.com.ar,www.matehost.com.ar
      - LETSENCRYPT_EMAIL=admin@matehost.com.ar

volumes:
  certs:
  html:
  vhostd:
  confd:`

**Comment by pablokbs** [comment]
Se ve bien eso, pareciera que tenes cloudflare en el medio y eso puede estar causando el conflicto, probá apuntar el dns de `www.matehost.com.ar` y `matehost.com.ar` a tu server con docker.

**Comment by Jnioms** [comment]
Ya tengo el CNAME redireccionando a `matehost.com.ar` directamente, decis que lo cambie por un record A tambien? Y por las dudas voy a esperar a que salga otra version y probar crear un subdominio a ver si por algun bug no toma correctamente los dominios separados por coma o algo. Gracias por la ayuda de todas formas! Si queres podes cerrarlo y despues de probar todo, vuelvo a abrir un ticket si sigo con problemas

**Comment by pablokbs** [comment]
Estoy seguro que no es un problema de lets encrypt con muchos subdominios, yo he usado muchos subdominios mil veces y no hay drama, tenés que sacar la variable del medio que es cloudflare para asegurarte que anda bien sin eso.

Dale lo cierro y cualquier cosa avisas
