### ISSUE TITLE
Auth de Poste.io con Ldap por Dominio

### ISSUE THREAD

**Issue by cavazquez** [pablokbs/peladonerd#113]
Hola, Como va? Queria consultar si se puede que Poste.io toma varios ldap y que cada uno dependa de un Dominio.

Algo que pueda hacer es obtener la lista de usuarios de  los ldap cada x cantidad de horas y agregalos mediante un correo. Los que estan actualzar las quotas o verificar si tienen que estar activas o no. 

Pero lo que no logro entender es como obtener la contraseña porque en el ldap esta encriptado en sha256. 

Puede directamente intentar verificar desde ldap?

**Comment by pablokbs** [comment]
Pareciera que no se puede, pero tal vez podés pedir que lo agreguen en el tracker de ellos: https://bitbucket.org/analogic/mailserver/issues/new

**Comment by cavazquez** [comment]
Conoces algun sistema que pueda hacer eso? Mailcow si se puede?

**Comment by pablokbs** [comment]
Fijate [zimbra](https://www.zimbra.com/)

**Comment by cavazquez** [comment]
He usado Zimbra pero su control anti-spam no esta tan bueno, no es que podes integrarlo con spamd. El backup tambien es un problema ya que siempre lo exporta distinto y no pueden ser incrementales o que un snapshot de zfs solo guarde las diferencias.

**Comment by cavazquez** [comment]
Gracias por la ayuda.
