### ISSUE TITLE
Como agregar la variable entorno para terraform?

### ISSUE THREAD

**Issue by fradducho** [pablokbs/peladonerd#12]
Hola Otra vez.
He intentado mirar como agregar la variable entorno 'TR_VAR_digitalocean_tocken' para que pueda ser utilizada por terraform?

Es posible que nos informes? 

He intentado agregando  lo siguiente en la linea de comandos.

"Env TR_VAR_digitalocean_toeken="MitockenAPIDigitalOcean"

Se agrega pero cuando doy clear a la terminal y vuelvo a teclear "env" para mostar todas  no me sale.  No he dado terraform init y apply por que entieno que fallara. Al no verla yo en la lista.

Muchas Gracias

**Comment by pablokbs** [comment]
Perdón por la demora en la respuesta

Para agregar la variable tenes que hacer:

`export TF_VAR_digitalocean_token=mitoken"

La otra que podés hacer es agregar esa misma linea en tu archivo `.bashrc` ... de esa forma siempre la vas a tener disponible cuando abras la terminal, saludos!
