### ISSUE TITLE
AGREGAR PROTOCOLO OPENGPG

### ISSUE THREAD

**Issue by FavioRonaldo** [pablokbs/peladonerd#120]
SE PUEDE AGREGAR EL PROTOCOLO GPG AL SERVIDOR DE CORREO ?

**Comment by pablomenino** [comment]
Se puede usar como addon en el cliente, pero vos decís si se puede agregar a Poste?

en ese caso esta seria la respuesta.

https://bitbucket.org/analogic/mailserver/issues/340/pgp-email-signing-in-posteio-pro

**Comment by FavioRonaldo** [comment]
GRACIAS!!
