### ISSUE TITLE
Problema con Exchange

### ISSUE THREAD

**Issue by emaita4x4** [pablokbs/peladonerd#122]
Buenas tardes.

Revisando tus videos vi uno que me parecio interesante ya que actualmente tengo un servidor de correo en exchange y mis correos llegan a SPAM cuando los envio a Gmail o hotmail.

Alguna opinion para arreglar esto?

**Comment by dbuenhombre** [comment]
utiliza algun servicio como sendgrind para hacer smart host. Estos servicio suelen tener ip verificadas y te quitaras muchos problemas para la emision.

en ibm cloud tienes un tramo gratuito que te da 15000 correos mensuales.
