### ISSUE TITLE
Duda con respecto a Nginx y Docker

### ISSUE THREAD

**Issue by nicolasegp** [pablokbs/peladonerd#129]
Buenas! me llamo Nicolás y soy bastante nuevo en esto de docker, entiendo el concepto de docker de instanciar aplicaciones con todas sus dependencias para evitar problemas de compatibilidad y eso me parece muy genial. En linux servicios como snap y flatpak hacen lo mismo para evitar romper una app.

Pero ahora, mi duda es a nivel de Nginx y múltiples sitios, he visto que todo el mundo recomienda **Reverse Proxy** y montar cada sitio en un contenedor distinto, entonces.

### ¿Cuál es el beneficio de utilizar varios contenedores de Nginx en vez de uno solo?

Se que se puede hacer balanceo de carga, pero siempre que veo trabajan en el mismo servidor, solo levantan distintos contenedores 🤔

entonces aquí mi duda, no es mas eficiente a nivel de recursos tener una sola instancia de Nginx y que sea el quien maneje las peticiones?

**Comment by cavazquez** [comment]
Te contesto. En mi laburo tenemos muchos wordpress.. algunos en la ultima version y otros en la version 3.5.1.. esta ultima version no funciona con  Ubuntu 20.04 porque soportan hasta php5.6 entonces no podes ponerlo todo junto. Tambien las bases de datos pueden estar configuradas de manera distinta. En pocas palabras, separlo te ayuda a evitar problemas a futuro cuando un proyecto requiera algo que otro no . Tambien es mas facil migrar un proyecto simplemente migrando el container.

**Comment by nicolasegp** [comment]
muchas gracias @cavazquez la verdad es que lo estaba viendo a nivel de desarrollador y quizás mi solución sería solo tener 2 contenedores con las versiones que se necesiten y así sectorizarlo

pero lo veo mejor con el tema de la migración, muchas gracias por responder

Saludos
