### ISSUE TITLE
Escalar servicios

### ISSUE THREAD

**Issue by mariooc** [pablokbs/peladonerd#13]
Buenas Pelado,

Hay alguna manera de escalar servicios (no nginx) y  agregar un load balancer

Ejemplo:
   tengo un script en python que expone un puerto para realizar una una tarea
   lo que quisiera es tener n instancias de ese servicio y tener un load balancer que derive las 
   requests.

hay algo que resuelva este problema?

**Comment by pablokbs** [comment]
Estamos hablando de Kubernetes u otra cosa?

**Comment by mariooc** [comment]
por ahora solo con docker
estoy por aprendiendo k8s

**Comment by pablokbs** [comment]
Bien, para eso podrias usar docker swarm y servicios (de docker swarm) para balancear la carga entre tus contenedores. Hice un video de docker swarm [acá](https://youtu.be/jRYRC3ZZPW8)
