### ISSUE TITLE
image is not correct

### ISSUE THREAD

**Issue by davic80** [pablokbs/peladonerd#138]
https://github.com/pablokbs/peladonerd/blob/21ab0a2b5c0723eeb0c77052481e45b28100ac7d/raspi/7/docker-compose.yaml#L20

Image should be:     image: jrcs/letsencrypt-nginx-proxy-companion:stable

**Comment by pablokbs** [comment]
hacete un PR y lo mergeamos

**Comment by davic80** [comment]
abierta!
