### ISSUE TITLE
Nginx-Proxy a endpoint en lugar de DNS

### ISSUE THREAD

**Issue by fernaper** [pablokbs/peladonerd#147]
Buenas, ahora mismo estoy trabajando en un proyecto en el que me sería muy útil la funcionalidad de Nginx-proxy junto con lets encrypt companion de redirigir a otros contenedores a través de HTTPS.

El problema es que lo hace utilizando un DNS para cada contenedor (hasta donde tengo entendido). Mi intención es que todos usen el mismo DNS pero a diferentes endpoints (por ejemplo: / para una API, /wp para un wordpress, /kb a kibana...).

Se hacer esto con el contenedor de Nginx y de hecho lo he probado y ha funcionado. El problema es que generar un certificado para usar HTTPS de esta manera no es fácil (incluso usando una imagen como certbot, te requiere primero que generes los certificados, esto es algo que quiero evitar hacer manualmente).

No sé si esta funcionalidad existe o alguien ya ha creado una imagen con esta funcionalidad, eso es precisamente lo que quería preguntar. ¿Existe?

Me encantaría que me contestéis incluso si no conocéis ninguna, si ese es el caso, no tengo problema en crearla yo y compartirla, básicamente lo pregunto para evitar re inventar la rueda, al fin y al cabo, me parece una funcionalidad que sería útil para mucha gente.

Gracias de antemano!

**Comment by paganuzzi** [comment]
hola existe [nginx proxy manager](https://nginxproxymanager.com/) que te permite especificar paths para un dominio y hacer lo que vos queres, ademas gestiona los certificados con letsencrypt

**Comment by fernaper** [comment]
Buenas!
Gracias por la recomendación voy a probarlo y darle una vuelta. Quizá me quede con él para la versión final.
Aún así, mi intención inicial era tener un contenedor lo más pequeño posible, sin funcionalidades de más (nginx proxy manager tiene, por ejemplo, una interfaz web, etc.)

¿No existe ninguna versión que haga esto mismo sin todas las funcionalidades extra?

**Comment by paganuzzi** [comment]
si es verdad, en mi caso opte por el manager porque es mas comodo de configurar
