### ISSUE TITLE
conexión entre contenedores

### ISSUE THREAD

**Issue by juan-dav** [pablokbs/peladonerd#15]
Estoy realizando una aplicación en php, me todo que realizar un servicio web más en java (y lo empaquete en otro contenedor) porque así lo requería el cual tiene que ser consumido desde la aplicación de php, a la hora de intentar consumir este no se como consumirlo ya que como son 2 contenedores diferentes van a tener ip's diferentes y no quiero quemar las ip's ya que supongo que es una mala practica. me podrían ayudar para saber como coger la ip del contenedor sin quemarla en el código?

**Comment by pablokbs** [comment]
Cómo estás corriendo los contenedores? A mano? Docker compose ? Tienes que
usar links

**Comment by faritvidal** [comment]
@juan-dav  para consumir el servicio desde otro contenedor tiene que hacer referencia al mismo, o usar el nombre del contenedor, esto por que a nivel de docker especificamente de networking se usa clase B en las ip que se asignan a cada contenedor por lo cual no se necesita router para que se pueda ver pero como son dinamicas no te va a servir usar uno estatica por que al relanzar contenedor estos pueden cambiar de ip, como se traduce esto tiene que asegurarte que ambos contenedores esten en la misma network y una vez hecho esto hace el link de un docker a otro, especificamente como este ejemplo

> 
version: "3.7"
services:
  web:
    build: .
    **depends_on:
      - db
      - redis**
  redis:
    image: redis
  db:
    image: postgres
>
