### ISSUE TITLE
Poste.io en Raspberry Pi

### ISSUE THREAD

**Issue by FrossGus** [pablokbs/peladonerd#150]
Hola.
Les hago una consulta. Se puede instalar Poste.io en una Raspberry Pi ??.
En el caso de una respuesta afirmativa, como se procede ??

Saludos.

Gustavo

**Comment by paganuzzi** [comment]
hola como va la imagen oficial de poste en dockerhub esta solo para amd64 y si haces una busqueda no encotras ninguna para arm asi que lo unico que queda es que la realices vos.

**Comment by Goro2030** [comment]
No, con la imagen que esta en docker.io no se puede porque es para amd64 :(

**Comment by Goro2030** [comment]
@pablokbs , ya se puede cerrar este Issue :)
