### ISSUE TITLE
Raspberry lag

### ISSUE THREAD

**Issue by bsmlazo** [pablokbs/peladonerd#160]
Hola Pelado!
Tengo un problema con mi raspberry, cuando en el docker-compose especifico los puertos, tengo lag conectado por ssh. La única forma de solucionarlo ha sido utilizando la opción network_mode: host.
El problema es que hay contenedores que utilizan los mismo puertos y no los puedo cambiar, no entiendo que pasa!!
![image](https://user-images.githubusercontent.com/20421050/116940818-7a9c2200-ac3c-11eb-8a00-de03c8c298d9.png)
Esa imagen es de un docker stats. Cuando corro, para este ejemplo, un nginx se presenta el problema (pasa con todos los contenedores).
Y así está el estado de la Rpi.
![image](https://user-images.githubusercontent.com/20421050/116940945-bdf69080-ac3c-11eb-96a5-14393bf98b76.png)

Gracias!!
Pelado muchas gracias por tu contenido y saludos desde Chile!

**Comment by Goro2030** [comment]
Podrias postear tu docker-compose, y el resultado de ejecutar el siguiente comando para ver que podria pasar? 

`docker ps --all --no-trunc`

Mas saludos desde yilito! :)

**Comment by bsmlazo** [comment]
@Goro2030 gracias por la respuesta mostro!
Encontré la solución y adivinen... el problema estaba entre el teclado y la silla jaja
Bien acá les dejo la respuesta por si a alguien le sirve en algún futuro.

El error lo tenía en la definición de mi ip estática de la rpi. EL archivo es **/etc/dhcpcd.conf**

Así estaba (lo dejé comentado en el archivo para no olvidarlo)
#interface eth0
#inform 192.168.1.103
#static routers=192.168.1.1
#static domain_name_servers=200.28.4.129 200.28.4.130

Y así es como debe estar

interface eth0
static ip_address=192.168.1.103/24
static routers=192.168.1.1
static domain_name_servers=200.28.4.129 200.28.4.130

Me dió dolores de cabeza, pero eso era!
Gracias de todos modos =)
