### ISSUE TITLE
error: unable to recognize "grafana-deployment.yaml": no matches for kind "Deployment" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by DiazRock** [pablokbs/peladonerd#164]
Estoy siguiendo el video sobre monitoreo con grafana y prometheus de un cluster de kubernetes, o sea [este](https://www.youtube.com/watch?v=_mJPvzMStPI). Estoy usando el repo que le corresponde, que es el [17](https://github.com/pablokbs/peladonerd/tree/master/kubernetes/17). 
Cuando hago `kubectl apply -f ./`, me da 
`error: unable to recognize "grafana-deployment.yaml": no matches for kind "Deployment" in version "apps/v1beta2"`. Lo que encontré como [recomendación](https://stackoverflow.com/questions/58481850/no-matches-for-kind-deployment-in-version-extensions-v1beta1) es cambiar de `apps/v1beta2` a `apps/v1`.

**Comment by pablokbs** [comment]
Sip, eso es porque cuando hice el video ese tipo de recurso estaba en beta, ahora es apps/v1. Hacete un PR y lo mergeamos ;)
