### ISSUE TITLE
Respecto al servidor xe correo en 1 minuto por tu video

### ISSUE THREAD

**Issue by lan73** [pablokbs/peladonerd#166]
Buenos días, a ver estoy con IP real , no tengo hosting, ni CPanel que eso se estila fuera de mi país por los proveedores de Internet, eso no exist en Cuba.

Lo que necesito es montar ese servidor de correo en ese breve tiempo sobre debian 9,

Es posible ??

**Comment by pablokbs** [comment]
Si claro, simplemente instalá docker en debian y después segui los pasos del video

**Comment by Casal0x** [comment]
@pablokbs te consulto algo parecido tengo un servidor local con ubuntu server, ya configurado con nginx y algunas api's de nodejs, algun problema si instalo docker y sigo el tuto o que pasos extra tendria q hacer, soy nuevo en docker estoy viendo un par de videos tuyos todavia

**Comment by Goro2030** [comment]
@Casal0x , no deberias tener problema, como te decia en el otro issue que abriste. Mejor cerrá aquel issue :)

**Comment by PinoVanDyk** [comment]
Hola Buen día Pelado Nerd(Pablokbs), aprovecho este post (esperando que no este incumpliendo con las normas) para preguntarte acerca del servidor de correo que hiciste en tu video, mencionas que se pueden hacer dominios virtuales yo cree 1 en el servidor que tengo pero no llegan los correos si puedo enviar y si lo mando de mi dominio principal si entran al virtual pero si envió de algún otro domino al virtual no llega ningún mensaje ni siquiera en el dashboard se ve actividad de entrada, sera que necesito hacer algo adicional
