### ISSUE TITLE
nginx vhost raspberry pi docker

### ISSUE THREAD

**Issue by Casal0x** [pablokbs/peladonerd#170]
Una consulta como configurarian en el caso del compose ese un vhost de una api q por ejemplo no este corriendo en otro contenedor sino por fuera.

**Comment by pablokbs** [comment]
tal vez lo que podrias hacer es un doble proxy, que jwilder/nginx-proxy lo mande a otro contenedor interno (que sea un simple nginx) y que eso mande el trafico a la api externa

**Comment by Casal0x** [comment]
me hablaste en japones jajaja recien termine tu curso de docker y estoy aprendiendo de todo un poco xD

**Comment by paganuzzi** [comment]
hola como va te dejo una lista de reproduccion del pelado para que veas https://youtube.com/playlist?list=PLqRCtm0kbeHD7A5f8Yft-5qFg-sgXvGzR﻿
