### ISSUE TITLE
Netdata, volumenes

### ISSUE THREAD

**Issue by tochimoreno** [pablokbs/peladonerd#171]
En el compose del proyecto NetData, me daba un error con volumenes.
Solucioné agregando un "./" en
- netdata-etc:/etc/netdata
para que quede:
- ./netdata-etc:/etc/netdata

**Comment by pablokbs** [comment]
Habria que ver que error te daba

**Comment by tochimoreno** [comment]
Algo así, como que no estaba definido el volumen.
Ahora tengo otro problema, y es que no puedo acceder a la interface.
El contenedor está corriendo, el netdata y el proxi, pero no no responde nadie en el 19999

**Comment by paganuzzi** [comment]
Hola Pablo el compose tenia algunos errores te hice un pr #172, saludos

**Comment by Goro2030** [comment]
Quedó funcionando bien ahora, incluso lee los containers de docker. Gracias por el PR. 

Che, viendo que la tenés clara ... el Netdata no me ve la memoria bien, por ejemplo no ve los volumenes de ZRAM como deberia ( tengo otra instalación con netdata nativo, no en docker, y las ve sin problema ). Que volumen habrá que exponer o que configuracion dentro de la definicion de plugins de netdata tocar para que los vea?

**Comment by paganuzzi** [comment]
hola como va, che yo no la tengo clara ni a palos jaja pero soy bastante rompe leyendo y probando todo lo que se me cruza ahi te dejo un link aparentemente podes deshabilitar ciertas metricas para que no les de bola netdata y asi aumentarle la performance capas en tu config esta ignorando zram y ahi tenes el problema [link](https://learn.netdata.cloud/docs/agent/collectors/proc.plugin#disabling-performance-metrics-for-individual-device-and-to-multiple-devices-by-device-type)
