### ISSUE TITLE
Cambio de versión en letsencript companion para varios/1: Creá tu sitio con SSL gratis con Docker y Let's encrypt

### ISSUE THREAD

**Issue by mstefa** [pablokbs/peladonerd#178]
Hola! Abro este issue porque estaba siguiendo el video del pelado "TU SITIO CON SSL GRATIS en DOCKER - Nginx Proxy" y no lo podía hacer funcionar. Así que leyendo un poquito encontré que hubo cambios importantes con el release de la v2. La docu oficial te redirige a este [link](https://github.com/nginx-proxy/acme-companion/issues/510). 

Este cambio implica principalmente que hay que generar un nuevo volumen ``` - acme: /etc/acme.sh ``` para permitir guardar las keys de la cuenta ACME y los certificados SSL.

Además de ese cambio encontré que en la documentación de docker hub te redirige a un repo donde muestra un docker-compose.yml que utiliza unas imágenes de owner: __nginxproxy__ 

Solo quería dejar comentada esta experiencia por si alguien se topa con este problema de nuevo. 

Y gracias pelado por tus videos, ¡sos un crack!

**Comment by pablokbs** [comment]
Podrías hacer un PR con esos cambios :)

**Comment by ralexrdz** [comment]
Yo estuve intentando con el nuevo acme-companion y tuve problemas para que me creara las configuraciones de nginx para escuchar el puerto 443. Terminé usando con mucho más gusto traefik

Si montas un repo de ejemplo con lo que se necesita para poner a funcionar de nuevo el nginx-proxy con docker-gen, te lo agradecería
