### ISSUE TITLE
Conectar al panel webmail desde fuera

### ISSUE THREAD

**Issue by javivi090** [pablokbs/peladonerd#18]
Hola!,

realize pruebas y envió y recibo mails con el un subdominio de duckdns, pero no consigo entrar al panel webmail o admin desde fuera.

Demasiado tiempo en responder aunque realizo un ping y no la ttl es de  **icmp_seq=3 ttl=54 time=45.2 ms**

Soy novato en esto. Muchas gracias
![image](https://user-images.githubusercontent.com/52855136/61170781-96699c00-a56e-11e9-86c5-465e89d326c5.png)

**Comment by pablokbs** [comment]
Hola! Podrias mostrar tu `docker-compose`? Me suena a que el problema es que no estás exponiendo el puerto  `443` en tu compose y/o te falta agregar esa redirección en tu router para este puerto

Saludos

**Comment by javivi090** [comment]
Lo estoy intentando desde casa con mi raspberry pi 3 y con duckdns, también intente con solo un wordpress y duckdns pero tenia el mismo error.


Versión de docker
![image](https://user-images.githubusercontent.com/52855136/61186317-1aea1680-a664-11e9-98b1-bead6c4e8614.png)

docker-compose.yaml
javi@ubuntu-18:~$ cat docker-compose.yaml
version: "3.4"
services:
    poste:
          image: analogic/poste.io
          restart: always
          network_mode: "host"
          expose:
            - 25
            - 80
            - 443
            - 110
            - 143
            - 465
            - 587
            - 993
            - 995
          volumes:
            - /root/mail-data:/data
          environment:
            - HTTPS=ON

    duckdns:
          image: linuxserver/duckdns
          container_name: duckdns
          environment:
            - PUID=1000 #optional
            - PGID=1000 #optional
            - TZ=Europe/Madrid
            - SUBDOMAINS=javivi,docscloud
            - TOKEN=1---------------------------8
            - LOG_FILE=false #optional
          volumes:
            - /path/to/appdata/config:/config #optional
          restart: unless-stopped

Dirección de puertos router
![image](https://user-images.githubusercontent.com/52855136/61186352-63093900-a664-11e9-910a-2c0f89d11bbd.png)

![image](https://user-images.githubusercontent.com/52855136/61186369-a6fc3e00-a664-11e9-8b99-153f677215a4.png)

![image](https://user-images.githubusercontent.com/52855136/61186424-9e583780-a665-11e9-85a8-f136b9cd1f0a.png)

**Comment by pablokbs** [comment]
No me parece que sea un problema con duckdns, me parece que tenes algun problema con tu router no redireccionando o bloqueando el puerto 443 (aunque veo que lo tenes bien configurado)

Podrias hacer un `curl -v javivi.duckdns.org/webmail/` ? y mostrarme la salida

De paso asegurate que el IP que te devuelve es tu ip publica real (esto lo podes checkear haciendo `curl ifconfig.me`)

**Comment by javivi090** [comment]
Resultado de curl -v javivi.duckdns.org/webmail/
```
javi@ubuntu-18:~$ curl -v javivi.duckdns.org/webmail/
*   Trying 81.184.96.159...
* TCP_NODELAY set
* Connected to javivi.duckdns.org (81.184.96.159) port 80 (#0)
> GET /webmail/ HTTP/1.1
> Host: javivi.duckdns.org
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Tue, 16 Jul 2019 15:07:08 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Location: https://javivi.duckdns.org/webmail/
<
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host javivi.duckdns.org left intact
javi@ubuntu-18:~$
```

Con curl ifconfig.me si que es mi IP publica pero he visto en la web de ifconfig.meque tiene X-Forwarded-For
```
javi@ubuntu-18:~$  curl ifconfig.me/forwarded
81.184.96.159, 216.239.38.21
```

Consultare también con la operadora, ya que no se me ocurre mas idea que no sea el propio router o operadora

**Comment by pablokbs** [comment]
Pareciera que estás detrás de un proxy que está recibiendo el trafico al `443` antes que tu nginx

**Comment by javivi090** [comment]
Gracias por la ayuda !!!
