### ISSUE TITLE
Pod en estado CrashLoopBackOff

### ISSUE THREAD

**Issue by jorgerojas919** [pablokbs/peladonerd#182]
Aplicando el kubectl aplly -f . del directorio ingress/ obtengo el siguiente mensaje en el log:

![log](https://user-images.githubusercontent.com/58471677/130695721-13920552-410f-4b8c-8340-1e68a7034580.PNG)

no estoy seguro si me falta algo (externo al repo) pero no me deja avanzar con el tutorial de youtube.

**Comment by kurodevs** [comment]
Tengo el mismo problema, realizo el tutorial desde docker desktop y no funciona, supiste como solucionarlo?

**Comment by infraGoga** [comment]
creo que pude solucionarlo reemplazando en el file 04 
apiVersion: rbac.authorization.k8s.io/v1beta1 por 
apiVersion:  rbac.authorization.k8s.io/v1 

dado que arrojaba :
#Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
