### ISSUE TITLE
Duda respecto de como conectar mi servidor node corroendo en un pod a una base de datos corriendo en otro pod del mismo cluster.

### ISSUE THREAD

**Issue by padapada09** [pablokbs/peladonerd#184]
Hola! Vi que en uno de tus videos dijiste que te mandemos ls consultas por acá. Así que si en algún momento llegas a tener tiempo para responderle a un simple mortal tratando de aprender kubernetes de la mano de tus maravillosos videos. Te lo agradeceré. 
Como puse en el titulo del issue, estoy pasando mis servidor a kubernetes (actualmente los levanto con dockercompose y me genera la red interna por defecto para que todos los contenedores se puedan conectar ) pero no me estaría funcionando cuando los levanto en pods en digital ocean. Si hay algún video que hayas hecho que hable de eso y me lo querés pasar (o alguien más que este leyendo esto me quiera guiar) será bienvenido. Saludos!

**Comment by pablokbs** [comment]
Buenas, para eso tenés que hacer un servicio de Kubernetes, hice videos de servicios acá:

https://www.youtube.com/watch?v=0iMEcrcfG5A

En el video de Kubernetes de 1,5 horas hablo de networking y explico servicios también: https://www.youtube.com/watch?v=DCoBcpOA7W4&t=3384s

**Comment by padapada09** [comment]
Sos crack! Gracias!
