### ISSUE TITLE
Cambio de puerto en POSTE

### ISSUE THREAD

**Issue by elgeografo** [pablokbs/peladonerd#186]
Estoy tratando de ejecutar un docker-compose con un POSTE. El caso es que no me deja correrlo porque tengo el puerto 80 ocupado por otro lado (tengo una web la cual no puedo cambiar de puerto).

He tratado de redirigir el puerto por medio de ports hacia el 81 pero no me deja. Sabéis si hay alguna manera de hacer esto sin necesidad de meter un proxy inverso?. Gracias.

BTW muy bueno el video

**Comment by gamba47** [comment]
Hola, con poner 

_ports:
    - '81:80'_   

Vas a tener el puerto disponible en el host usando el 81.

Igual no se porque no queres usar un reverse proxy, son una cosa maravillosa, si es porque no tenes un dominio para tu poste.io lo que podes hacer es en el archivo de hosts de tu pc editar y agregar una linea que te lleve a este dominio falso, no vas a poder tener SSL, pero me resulta siempre mas comodo poder llegar por nombre de red ( y sin meter puertos raros)

Saludos

**Comment by elgeografo** [comment]
Gracias por tu respuesta @gamba47. Ya lo he intentado como indicas y no llego al 81 (no he visto los logs, que sería lo suyo). Quito el puerto de expose y lo pongo en ports, pero tampoco funciona. Voy a ver que pasa en los logs y, si veo que se complica uso, como dices, el nginx.

Gracias amigo,

**Comment by gamba47** [comment]
Podrias compartir tu docker-compose.yaml y tambien la salida de estos comandos?

`docker-compose ps`

`docker ps`


Saludos!

**Comment by shadowsberg** [comment]
Buenos días, tengo la misma duda tengo una aplicacion Laravel corriendo con nginx, con un dominio principal, y un subdominio apuntando a las misma ip, al desplegar poste.io este choca en el puerto 80, no se que hacer para que los dos puedan convivir, soy novato en el tema de docker y servidores, si me pueden ayudar un poco se los agradeceria mucho.

**Comment by gamba47** [comment]
> Buenos días, tengo la misma duda tengo una aplicacion Laravel corriendo con nginx, con un dominio principal, y un subdominio apuntando a las misma ip, al desplegar poste.io este choca en el puerto 80, no se que hacer para que los dos puedan convivir, soy novato en el tema de docker y servidores, si me pueden ayudar un poco se los agradeceria mucho.

Tenes que usar algo como nginx-proxy manager para que use el puerto 80 y 443 y los puertos de ambos servicios no los expones en tu maquina, si no que le dan el trabajo al reverse proxy para que puedan recibir las peticiones en funcion del dominio al que estas queriendo ingresar.

De paso le podes poner SSL 
https://www.youtube.com/watch?v=0n9DLj2ndo4
