### ISSUE TITLE
No puedo recibir correos en poste

### ISSUE THREAD

**Issue by LuisSarmientoM** [pablokbs/peladonerd#189]
Deje de recibir los correos en poste, los puedo enviar, crear nuevos correos, etc pero cuando me envían uno no se recibe.

**Comment by jaweewo** [comment]
Tengo exactamente el mismo problema, estoy tratando de solventarlo.

**Comment by LuisSarmientoM** [comment]
Llevo 3 dias ya en esto, como no tengo información importante en los correos, e eliminado por completo el volume de docker y la carpeta de los correos asi como el contenedor e instalado y configurado todo de cero pero no me han funcionado aún, de hecho, los correos de prueba que envié con mi gmail personal han sido rechazados por completo y el correo se ve así

<img width="1105" alt="Captura de Pantalla 2021-11-30 a la(s) 6 40 24 p m" src="https://user-images.githubusercontent.com/42702720/144146033-d24684f3-5815-4f64-aba1-9a7753682f6c.png">

**Comment by jaweewo** [comment]
Por casualidad, tu tienes configurado un Reverse DNS contra la IP?

**Comment by LuisSarmientoM** [comment]
> Por casualidad, tu tienes configurado un Reverse DNS contra la IP?

Si, tengo varios subdominios que apuntan al mismo doplet de Digitalocean y con Nginx hago las redirecciones

**Comment by jaweewo** [comment]
Eso es el apartado donde apuntas un Dominio a una IP es decir, un DNS con registro A.
No obstante, es recomendable en correos usar un Reverse DNS, es decir, en digital ocean, podrás indicarle al dropplet un nombre de host.
Te pongo mi ejemplo en mi proveedor:
![image](https://user-images.githubusercontent.com/35831933/144296402-d7c34ce7-082b-4cab-a08c-7e3f6ceab24c.png)
Yo aún no he levantado la estructura que deseo, voy a realizar pruebas con el rDNS y te digo.
También te recomiendo, no enviarlo a gmail u otras entidades conocidas.
Prueba : https://www.mail-tester.com

**Comment by LuisSarmientoM** [comment]
Es que al poner ms datos de API de sendgrid puedo enviar correos desde poste y no me llegan a SPAM ni nada, solo que cuando intento enviarle un correo, por ejemplo al correo admin me lo rechaza.

Tengo un registro A que me redirecciona siempre al droplet e internamente se redirecciona con nginx.

**Comment by LuisSarmientoM** [comment]
@jaweewo Ya pudiste solucionar esto?

**Comment by gamba47** [comment]
> Llevo 3 dias ya en esto, como no tengo información importante en los correos, e eliminado por completo el volume de docker y la carpeta de los correos asi como el contenedor e instalado y configurado todo de cero pero no me han funcionado aún, de hecho, los correos de prueba que envié con mi gmail personal han sido rechazados por completo y el correo se ve así
> 
> <img alt="Captura de Pantalla 2021-11-30 a la(s) 6 40 24 p m" width="1105" src="https://user-images.githubusercontent.com/42702720/144146033-d24684f3-5815-4f64-aba1-9a7753682f6c.png">

Hola, el mensaje ahi es que poste.io no quiere recibir las peticiones, hay que mirar los logs

Para poder hacerlo interactivamente y no depender de gmail que envie el mail (puede encolarlo y demorar unos segundos) podes usar telnet y hablar con tu server, algo como esto https://www.dell.com/support/kbdoc/es-ar/000129267/como-probar-un-servidor-de-correo-electronico-con-el-cliente-telnet

**Comment by leadvic** [comment]
Hola, yo tengo el mismo problema, puedo enviar correos pero no los puedo recibir.
Estoy usando un servidor local (self-hosted), en el cual tengo nginx proxy manager (npm) y poste. Uso sendGrid con el dominio autenticado no obstante todavía no puedo descubrir cómo recibir los correos correctamente

**Comment by leadvic** [comment]
> 

Acabo de encontrar la solución que funcionase para mi... Mi problema era la opción "SSL/TLS Recommender" de Cloudflare, al quitar esta opción pude comenzar a recibir correos electrónicos sin ningún problema! Espero de algo les sirva ;)

![image](https://user-images.githubusercontent.com/38141591/155893544-5257ff9e-3d33-4101-a6dd-c91cce7ba765.png)

**Comment by LuisSarmientoM** [comment]
Mi servidor está en DigitalOcean.
