### ISSUE TITLE
POSTE.IO DOCKERIZED y NGINX sin contenedor.

### ISSUE THREAD

**Issue by emancia27** [pablokbs/peladonerd#190]
Hola Buenos días.

Soy nuevo con todo esto de poste.io y nunca lo he instalado la verdad. Me gustaría instalarlo junto con Nginx (pero no en forma de contenedor).

Me pudieran ayudar con algún tutorial o videos, ya que he visto alguna documentación pero me confunde un poco. 

Les estaré muy agradecido.

Saludos.

**Comment by gamba47** [comment]
No me había dado cuenta, pero poste.io no tiene los archivos a la vista para poder instalarlo "a la antigua".

Lo más cerca que vas a estar es leyendo el dockerfile, ahi estan los pasos de como crear un poste.io, algo como esto:  https://hub.docker.com/layers/analogic/poste.io/2.3.5/images/sha256-2c0c5f1eeb9bc2c0e1625edb41581b914d8d1b26dce44ce8fec405177b2e053e?context=explore

Aún asi te recomiendo mirar docker, es una buena herramienta y te va a abrir la cabeza para usarlo en el futuro.

Saludos!

**Comment by crfactura** [comment]
La forma soportada por los creadores es con docker, esta así hasta para actualizar y es mas fácil.

**Comment by keadanis** [comment]
La forma mas sencilla es con docker y le será más sencillo para cuando lo quieras actualizar.

**Comment by tinolin** [comment]
> Hola Buenos días.
> 
> Soy nuevo con todo esto de poste.io y nunca lo he instalado la verdad. Me gustaría instalarlo junto con Nginx (pero no en forma de contenedor).
> 
> Me pudieran ayudar con algún tutorial o videos, ya que he visto alguna documentación pero me confunde un poco.
> 
> Les estaré muy agradecido.
> 
> Saludos.

La gran pregunta es ¿y para que queres eso?

**Comment by perezale** [comment]
Hola emancia!

Creo que entiendo por donde viene la pregunta. Queres aprovechar un server para tener tu nginx y tambien el mail server?

Con o sin contenedores, (probablemente) vas a querer exponer tu nginx en los puertos 80 y 443 del server (_host_), que entrarían en conflicto con los del container del pelado. 

Podes ver que el mail server usa los mismos puertos 80 y 443 y otros mas para mail... ([link](https://youtu.be/K4-uD1VHCz0?t=149)). Esto es (si no le pifio) para el webmail (el gestor web, al que despues le ponen los certificados).

Como dice el pelade, con el network "host" se facilita la configuracion de red y el servicio de mail va a tomar los puertos del host que estan ahi listados. (Como tu nginx "con o sin contenedor" también lo va a querer hacer con estos dos, entrando en conflicto). 

En tu caso asumo que queres hacer de tu nginx la puerta de entrada "web" del host (80/443). 

Ahora, si quisieras tener los dos en un mismo servidor (siendo o no contenedores), pienso --para empezar-- estos detalles pensando en el reverse proxy que dice el pela.

* En el mail server, tendrias que dejar de usar el network host, y aplicar reglas en ```ports``` de docker compose para exponer el puerto 80 y 443 en otro lugar y el resto como están. Sería como convertis esos ```expose``` en algo mas controlado.
```
ports:   
  - 4443:443   
  - 8080:80 
  - 25:25
  - ...
```
* Usar el nginx como "reverse proxy" para llegar a tu webmail, que ahora está escondido en 8080 y 4443.  Armar el reverse proxy es configurar un ```site``` mas en tu nginx, particularmente el mail.dominio.com. Queda de tu lado esa configuración y la generación de certificados.
* Agregar nginx al IaC ¿opcional?
* otros problemas que surgen en el camino 😅 

Creo que la practica de "copar" la red del host viene de estar escribiendo IaC con terraform. Es mas facil levantar un droplet solo con el mail server con los puertos default que andar haciendo manejes con los puertos.

Personalmente me gusta como está 1 droplet - mail server

**Comment by snaven10** [comment]
Pregunta eso es para el apartado de ports y en expose que puesrto pongo
