### ISSUE TITLE
Droplet digital ocean con varios dominios y poste io

### ISSUE THREAD

**Issue by fedeaguilera** [pablokbs/peladonerd#192]
Buenas para todos. Seguramente algun experimentado sepa orientarme. Actualemente tengo una estructura montada en un droplet de digital ocean con 3 aplicaciones node corriendo ambas con dominio independiente con un proxy de nginx. Mi pregunta es la siguiente. Tengo pensando lo siguiente. Crear otro droplet para montar los correos correspondientes a esos dominios. Debo crear un droplet por cada dominio o con un solo y 3 contenedores poste io funcionara. De ser asi que configuracion extra debo utilizar. La idea de esta migracion es abaratar costos en servicios externos de correo. Desde ya gracias por su tiempo pelado y comunidad.

**Comment by paganuzzi** [comment]
hola poste tiene virtual domains por ahi con un solo server podes administrar correos de los 3 dominios

**Comment by fedeaguilera** [comment]
> hola poste tiene virtual domains por ahi con un solo server podes administrar correos de los 3 dominios

Juan gracias por responder. Debo apuntar los mx a ese droplet y listo ?o requiere alguna otra configuración el docker-compose.yaml?

**Comment by marcelodf12** [comment]
Técnicamente poste te da la posibilidad de configurar varios dominios al mismo server. El problema está que no vas a poder configurar el rDNS para los 3 dominios. Solo podrás configurar uno solo, y esto tiene como consecuencia que Gmail o Hotmail marquen automáticamente tus correos como spam. Si esto no te importa adelante. Caso contrario vas a tener que tener un droplet por cada instancia. Al menos yo en digitalOcean no encontré de hacerlo diferente.

**Comment by fedeaguilera** [comment]
> Técnicamente poste te da la posibilidad de configurar varios dominios al mismo server. El problema está que no vas a poder configurar el rDNS para los 3 dominios. Solo podrás configurar uno solo, y esto tiene como consecuencia que Gmail o Hotmail marquen automáticamente tus correos como spam. Si esto no te importa adelante. Caso contrario vas a tener que tener un droplet por cada instancia. Al menos yo en digitalOcean no encontré de hacerlo diferente.

Hola. Gracias por responder. No eso tendrian impacto negativo. Agregado eñ registro PTR no funcionara?

**Comment by yojota** [comment]
@fedeaguilera en mi experiencia de abaratar costos con correos fue saber cantidad de correos que va a manejar cada uno de esos servidores, zohomail que funciona muy bien cobraba 1 dolar por cada cuenta. Si vas a manejar correo y no querés renegar con que te marquen como spam la mejor idea es ir por un droplet que maneje cada dominio de correo. Si no vas a entrar a configurar muchas cosas y perder tiempo en mantenimiento. Pero bueno es mi punto de vista. Siempre ser linyeniero y encontrar la solución más barata a veces es mas caro en tiempo.

**Comment by fedeaguilera** [comment]
> @fedeaguilera en mi experiencia de abaratar costos con correos fue saber cantidad de correos que va a manejar cada uno de esos servidores, zohomail que funciona muy bien cobraba 1 dolar por cada cuenta. Si vas a manejar correo y no querés renegar con que te marquen como spam la mejor idea es ir por un droplet que maneje cada dominio de correo. Si no vas a entrar a configurar muchas cosas y perder tiempo en mantenimiento. Pero bueno es mi punto de vista. Siempre ser linyeniero y encontrar la solución más barata a veces es mas caro en tiempo.

Gracias por responder colega. Si el problema es q tiene un solo correo y querian mas google workbench cobra 5 dolares por correo. Entonces estaba buscando una solucion mas economica. Gracias por compartir tu experiencia.
