### ISSUE TITLE
Docker Storage

### ISSUE THREAD

**Issue by danielbaldovino** [pablokbs/peladonerd#196]
Hola, no sé si este sea el sitio, pero, no vi la pestaña de discusiones.

Antes que nada, muchas gracias a @pablokbs por todo el conocimiento que comparte, sin duda alguna vale mucho todo lo que aporta.

Ahora bien, he estado haciendo un par de cosas con Docker y recientemente me encontré con que cada contenedor tiene un límite de almacenamiento; en este caso, un contenedor necesitaba tener más o menos 10GB de unos paquetes de lenguaje y daba error por espacio insuficiente.

He estado leyendo un poco (https://docs.docker.com/storage/storagedriver/select-storage-driver/) pero, no veo cómo asignar más espacio al contenedor, o que corra sin restricción como cuando se trata de la CPU.

¿Alguna idea?

**Comment by pablokbs** [comment]
> he estado haciendo un par de cosas con Docker y recientemente me encontré con que cada contenedor tiene un límite de almacenamiento

Donde viste eso? docker no limita el espacio, tal vez tu configuración de Docker Desktop es lo que te está limitando

**Comment by Goro2030** [comment]
> > he estado haciendo un par de cosas con Docker y recientemente me encontré con que cada contenedor tiene un límite de almacenamiento
> 
> Donde viste eso? docker no limita el espacio, tal vez tu configuración de Docker Desktop es lo que te está limitando

Ayyy esta gente que solo usa Linux :)

En Windoze, al usar Docker Desktop, viene limitado el espacio en disco por cada instancia. Tenes que ir a "Settings" ( La ruedita ), luego "Docker Engine" y ahí en la 4ta linea, clavale los GB que quieras.

{
  "builder": {
    "gc": {
      **"defaultKeepStorage": "20GB",**
      "enabled": true
    }
  },
  "debug": false,
  "experimental": false,
  "features": {
    "buildkit": true
  },
  "insecure-registries": [],
  "registry-mirrors": []
}

**Comment by danielbaldovino** [comment]
Wow! no pensé que respondieran tan rápido, no he tenido buenas experiencias en otros foros, muchas gracias por estar atentos y por la ayuda.

Ya que pablo mencionó que tal límite no existe, volví a revistar el tema con más detenimiento y encontré que no se refería al almacenamiento, sino a la RAM ... con eso ajusté los valores del servidor y listo.

![image](https://user-images.githubusercontent.com/98127885/151043687-e0561a0f-24b8-46fc-b382-e8389e332b08.png)

De nuevo gracias, saludos.
