### ISSUE TITLE
Poste.io no funciona con Codeigniter 

### ISSUE THREAD

**Issue by lukmagg** [pablokbs/peladonerd#202]
Buenas pelado, muchas gracias por los videos. me sirven un monton para resolver problemas en el trabajo.

Ahora mismo estoy con un error que no puedo solucionar hace 3 dias ya!

Estoy intentando enviar emails desde Codeigniter 4 con la libreria email del mismo framework.

Tengo un servidor Poste.io colgado en un hosting y he configurado el Codeigniter 4 de distintas formas pero siempre me devuelve el siguiente error: unable to send email using PHP SMTP. Your server might not be configured to send mail using this method

Lo raro es que desde el navegador envia emails perfectamente. Solo no funciona desde Codeigniter

**Comment by plencovich** [comment]
@lukmagg codeigniter siempre fue problemático en ese sentido, tanto en la 3 (siempre use phpmailer ); para la versión 4 te recomiendo que revises la configuración y parámetros como:
$mailPath, $SMTPCrypto

y si queres comparti el debug, $email->printDebugger(); para ver que error te está dando en concreto. caso contrario te recomiendo que uses phpmailer y te haces una librería que sirva de interfaz

**Comment by lukmagg** [comment]
@plencovich el $email->printDebugger() me muestra esto: unable to send email using PHP SMTP. Your server might not be configured to send mail using this method

'SMTPCrypto' => 'tls'
'SMTPPort' => 587,
'protocol' => 'smtp'


En mailpath no he puesto nada, no se que poner ahi. Por defecto viene /usr/sbin/sendmail.

**Comment by plencovich** [comment]
@lukmagg probaste con el puerto 465 y tls? ya que el 587 es starttls e iría con ssl.
