### ISSUE TITLE
Sobre Nginx y Let'sEncrypt

### ISSUE THREAD

**Issue by edwin5050** [pablokbs/peladonerd#208]
Hola Pelado, como haria si en mi docker-compose tengo una pagina normal y uso nginx pero tambien tengo un api con express que corre en un puerto 3000, como haria para que el nginx proxy le genere el SSL tambien a ese contenedor, yo lo tengo en un subdominio por ejm la pagina en el root www.mipagina.com pero el api la tengo en dev.mipagina.com.

gracias de antemano

**Comment by pablokbs** [comment]
Podes usar la variable VIRTUAL_PORT para especificar un puerto diferente al 80:

https://github.com/pablokbs/peladonerd/blob/57598acdb31830adf2f92cbfacbc46b8e1b69266/v2m/37/docker-compose.yml#L110-L111
