### ISSUE TITLE
Consulta sobre Poste.io

### ISSUE THREAD

**Issue by SkyTrack2** [pablokbs/peladonerd#209]
Estamos tratando de migrar en mi trabajo de un exchange a alguna otra solucion, Poste.io es compatible con lista de contactos? y lo otro es compatible con Active directory? desde ya muchas gracias. Me estoy iniciando en este tema de la infraestructura

**Comment by Goro2030** [comment]
No y no. Poste.IO es basicamente un server de correo basico, pop3, imap, smtp, etc.

De hecho es lo primero que sale en su website https://poste.io 

SMTP + IMAP + POP3 + Antispam + Antivirus
Web administration + Web email
