### ISSUE TITLE
Poste.io no envia correos

### ISSUE THREAD

**Issue by Arles96** [pablokbs/peladonerd#213]
Segui todos los pasos del video y se realizo de manera exitosa la configuración. Pero tengo un problema, quise realizar una prueba de enviar un correo a mi correo de gmail, pero nunca lo recibio. Pero el Poste.io si recibe correos. ¿Alguién tiene el mismo problema?

**Comment by cdecarlos** [comment]
Mismo problema, buscando info...

**Comment by perezale** [comment]
🤔 fui a probar mi instalación y sigue andando bien.
Mande desde el webmail y recibí en SPAM. Pero anda!

Version 2.3.6

**Comment by yojota** [comment]
se que es medio tarde, pero @Arles96 podrás buscar logs y enviar como para saber por donde puede venir el problema. A ver si no son los registros SPF o DKIM que capaz por eso no podes enviar a gmail. 
Pueden ser varias cosas acá tenes un lugar donde validar cuales son los puntos que falla tu servidor de correo 
https://www.mail-tester.com/
Como para saber que cosas están y no están en tu configuración

**Comment by agustinvergara** [comment]
estoy en la misma, he probado todos los registros dns y hasta intente implementar sendgrid pero nada de nada. He estado focot lo unico que se me ocurre es que tenga que ver ya con el dominio.
