### ISSUE TITLE
/etc/default/docker vs /lib/systemd/system/docker.service  ¿cual es mejor?

### ISSUE THREAD

**Issue by Zakspeed** [pablokbs/peladonerd#22]
¿estas 2 opciones cual es la mejor?

`sudo vim /etc/default/docker`
- Agregar esta linea al final con la ruta de tu disco externo montado;
export DOCKER_TMPDIR="/mnt/storage/docker-tmp"

A mi me es incompatible con: 
`sudo nano /lib/systemd/system/docker.service`
- agregar en la linea "-g /media/pi/USB" (Optionally, store containers in an external USB drive. Change the following line);
ExecStart=/usr/bin/dockerd -g /media/pi/USB -H fd:// --containerd=/run/containerd/containerd.sock

¿cual seria la mejor opcion para que no carge la SD en la Raspberry?

* igual no es este el espacio donde insertar esta duda pero, me pierdo en "GitHub"

**Comment by pablokbs** [comment]
No hay problema, es buena pregunta, basicamente es lo mismo, cualquiera de las 2 opciones hace exactamente lo mismo y no tiene ninguna ventaja ninguna de las 2. A mi me gusta usar el `/etc/default/docker` porque es mas facil de visualizar si tenes muchas opciones

Saludos!
