### ISSUE TITLE
Poste.io no funciona

### ISSUE THREAD

**Issue by gexzam** [pablokbs/peladonerd#223]
He seguido todos los pasos del video y he revisado todos los archivos del repo.
Todo está bien, no me arroja ningún error.
Compré mi dominio en IONOS y ya apunté las DNS a Digital Ocean (DO)
He configurado en DO todas las DNS como dice en el repo.
He configurado el .yaml tal cual dice en el repo.
Cuando voy a mi dominio mail.midominio.com, simplemente no muestra nada.

**Comment by pablokbs** [comment]
no muestra nada que quiere decir? error 404? 500? no resuelve? error de conexion?

**Comment by pablokbs** [comment]
habria que leer logs logs para entender que pasa, pero lo mas seguro es que te bloqueen la salida al puerto 25, eso lo hacen todos los proveedores de servidores, tenés que pedir que te lo habiliten

**Comment by gexzam** [comment]
Debo escribirle al soporte de DO?

**Comment by pablokbs** [comment]
primero hay que leer el log y entender que pasa

**Comment by gexzam** [comment]
Por favor, indícame cómo puedo obtener el log o mándame un link para yo hacerlo.

**Comment by pablokbs** [comment]
https://docs.docker.com/engine/reference/commandline/compose_logs/

**Comment by gexzam** [comment]
Perfecto, lo postearé más tarde. Muchas gracias man.

**Comment by gexzam** [comment]
Hola Pablo, solo quería aportar [estas instrucciones](https://charm-lute-62b.notion.site/Dokku-app-posteio-96a4184a148f411fb62d96e138b9d9f2) a la comunidad:

**Comment by mark33sv** [comment]
Saludos  @**Pablokbs** desde El  Salvador.
Yo he instalado todo a "pata' como decimos por aquí.
1.- No uso DOcker, ni docker compose
2.- No Uso Terraform
3.-Si esta en DigitalOcean
  3.a Un sitio esta direccionado de su viejo webhosting, aunque me ha costado darle de baja al DNS con el key de autorizacion, para pasar el domino (transfer) por ejemplo a namecheap.
Aunque me funciona perfecto en DO or el momento.
Tus scripts es obvio hacen uso de ello par asu instalacion y configuración.
Tengo dos sitos listos.
Hay alguna otra manera de realizar la instlacion de poste.io sin problemas al no contar con Terraform y Docker compose?
Por el momento seguiré buscando configuración e instalaciónde poste.io
