### ISSUE TITLE
Ngnix en docker

### ISSUE THREAD

**Issue by claclin** [pablokbs/peladonerd#227]
Al instalar ngnix con docker no veo dentro del docker /etc/ngnix los directorios sites-available y sites-enabled

**Comment by c0da** [comment]
Qué imagen estás usando?

**Comment by paganuzzi** [comment]
en esa imagen de nginx tenes /etc/nginx/nginx.conf la configuracion general y en /etc/nginx/conf.d las configuraciones de los sitios que vas a usar.

**Comment by claclin** [comment]
Perdonad, pero donde configuro los virtual hosts? algun ejemplo o muestra? viendo el video de Instalando y configurando Nginx hay configura un fichero llamado default que ya esta hecho y solo modifica unos parametros. Donde encuentro yo ese fichero?

**Comment by c0da** [comment]
El "default.conf" está en /etc/nginx/conf.d/. 

Si vas a necesitar configurar varios virtualhosts, quizás te convenga usar nginx-proxy. Probaste con esto? https://www.youtube.com/watch?v=S2YFqf4L7l8

**Comment by claclin** [comment]
Ya intente lo del video, pero no se porque no se me certifica. Estoy usando WSL quizas sea algo de eso, no tiene acceso la entidad certificadora... El default ya lo vi pero no encontre las entradas de server que comentaba en el video.

**Comment by c0da** [comment]
Si estás usando WSL, tu entorno va a tener una IP privada (que se puede ver en windows, ejecutando ```wsl hostname -i``` en un cmd o powershell). La entidad certificadora necesita llegar desde internet al puerto 80 de tu "nginx-proxy" para verificar que lo que hayas puesto en la variable "LETSENCRYPT_HOST" es tuyo.

Por intentar simplificarlo, si usáramos como ejemplo "www.claclin.com" tendrías que:
- Tener un registro (A) en el DNS de tu dominio que apunte "www.claclin.com" a tu IP pública.
- En tu router/firewall, mapear (port forwarding) el puerto 80 contra el puerto 80 de tu entorno WSL

**Comment by claclin** [comment]
lo intentare asi... el comando wsl hostname -i no funciona en wsl
