### ISSUE TITLE
Resolver DynamicDNS en una A Record

### ISSUE THREAD

**Issue by j0nl1** [pablokbs/peladonerd#25]
Buenas!
De nuevo felicitarte por tu trabajo y hoy vengo con una pregunta que no consigo resolver.

He visto en tus vídeos que utilizas varios dominios que posees y se te resuelven en la ip de casa y no consigo saber cómo.

Actualmente tengo duckDNS pero claro no puedo utilizar una A record con el duckDNS ya que necesita de una ip.

Me gustaría saber que método utilizas para resolver el a record principal del dominio y que al final se transforma en la ip de tu hogar.

Gracias,
Un saludo

**Comment by pablokbs** [comment]
No te estoy entendiendo, el A record es una IP. El cliente de duckdns lo
que hace es actualizar el subdominio y lo apunta a la IP externa de tu casa

**Comment by j0nl1** [comment]
Basicamente preguntaba si hay alguna manera sencilla para tener un servidor en tu casa que apunte a un dominio. El problema aquí es que la ip es dinámica y cambia. He visto en vídeos que hacias trasteos desde casas y apuntabas directamente a dominios y me preguntba como lo hacias.

Gracias

**Comment by pablokbs** [comment]
Lo que yo haria seria tener un subdominio (en duckdns por ejemplo) y apuntar el www al CNAME que de duckdns, por ejemplo:

www.midominio.com -> tudominio.duckdns.org

En el FAQ de DuckDNS dan el mismo ejemplo:

![image](https://user-images.githubusercontent.com/4028336/63599665-6c0cf480-c598-11e9-827c-b2a69df7982a.png)

El tema es el root (`midominio.com`) no se puede apuntar a un CNAME (bueno, depende del proveedor de DNS, pero generalmente no lo permite porque viola las RFC de DNS [1](https://tools.ietf.org/html/rfc1912) [2](https://tools.ietf.org/html/rfc2181))

Pero fijate si podes con tu proveedor de DNS hacer lo que puse mas arriba

**Comment by j0nl1** [comment]
Lo que hacia esto es hacer como un forward de la dirección del dominio a la dirección que configuraba en el cname. Finalmente he optado por pagar para añadir zones en no-ip.
De todas formas si encuentras alguna solución en un futuro, molaría mucho un vídeo. Estuve pensando en montar mi propio dns handler con bind pero me pareció un poco tedioso, molaría otra vídeo de eso.

https://www.ionos.com/digitalguide/server/configuration/how-to-make-your-raspberry-pi-into-a-dns-server/

Gracias de nuevo!
