### ISSUE TITLE
Preguntas del video: CREÁ UN SERVER DE CORREO EN 1 MINUTO / V2M: Poste

### ISSUE THREAD

**Issue by KATalyzt36** [pablokbs/peladonerd#258]
Tengo una pc servidor en mi trabajo con Linux Mint, (Actualmente, quizas lo cambie dentro de poco) se puede hacer ahi? No entiendo nada de Docker jaja. Y en el dominio dice que me cobran como 50 dolares más al año para tener ese servicio, es realmente necesario o se hace con lo de este video? (Porque tambien vi otros que hacen lo mismo que FIrefox Relay (Redireccionamiento de correos)).
No pienso pagar más de 1 o 2 dolares por mes porque no me da el cuero vio 😂

**Comment by pateze** [comment]
Si, lo podés hacer en cualquier dispositivo. Si, es muy simple. Existe una versión gratuita y una paga: esta ultima incluye más features.
