### ISSUE TITLE
Link Erroneo video Ollama 

### ISSUE THREAD

**Issue by RicardoMaldonado93** [pablokbs/peladonerd#265]
Hola @pablokbs , como estas?

Queria avisarte, por si es un error, que en el Readme en la seccion de Varios, Cap 17, tiene mal el linkeo al video.
El mismo esta redireccionando a este [Como NaranjaX usa IA para su CI/CD?](https://youtu.be/gOJvQnC-7r8) en vez de [Probando OLLAMA](https://www.youtube.com/watch?v=OmLKfDoAfyM)

Saludos!

**Comment by pablokbs** [comment]
Hola. Podes meter un PR si querés 😉
