### ISSUE TITLE
minikube to Kind - Error al crear Cluster

### ISSUE THREAD

**Issue by hmunoz** [pablokbs/peladonerd#28]
Despues de instalar Kind.
creo el cluster: kind create cluster --config  kind-multi-node.yaml.
Hace todo el proceso bien.

kind-worker2 | running |   | - | kindest/node:v1.15.3 
kind-control-plane | running |   | - | kindest/node:v1.15.3 
kind-worker | running |   | - | kindest/node:v1.15.3

kubectl cluster-info
Kubernetes master is running at https://127.0.0.1:49453
KubeDNS is running at https://127.0.0.1:49453/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

<img width="989" alt="Captura de Pantalla 2019-08-31 a la(s) 18 29 57" src="https://user-images.githubusercontent.com/5365225/64069343-37471000-cc1e-11e9-85b9-4ac64311d70d.png">
[dump.txt](https://github.com/pablokbs/peladonerd/files/3562879/dump.txt)

**Comment by pablokbs** [comment]
Me parece que eso no es un error. Simplemente un mensaje que te dice que
podes debuggear si tenés algún problema tirando ese comando

Pero parece que todo te anda bien, si haces el export ese que te dice y
después hacés `kubectl get pods` te anda bien ?

Saludos

**Comment by hmunoz** [comment]
Ya esta, encontre el problema, mala mia.
Los path los configure en bash, y me pase a zsh despues de actualizar a osx Catalina.
pase los path a ~/.zshrc  y todo empezó a funcionar.
Hasta con la configuracion kind-multi-node.yaml.
Ahora ya puedo probar kind, porque con minikube se me tildaba mucho
