### ISSUE TITLE
usar helm con Kind

### ISSUE THREAD

**Issue by hmunoz** [pablokbs/peladonerd#29]
Con minikube no tuve problemas usando helm, pero con un cluster de con Kind se ve que faltan configurar algunas cosas

helm install --name my-moodle stable/moodle
Error: release my-moodle failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"

Trate de arreglar esto, pero termine de romper el cluster, es obvio que me falta configurar un contexto de dev y prod con los permisos.

Cualquier guia es bien recibida

**Comment by hmunoz** [comment]
Encontré los comando que lo arreglan, pero no los entiendo bien.
```
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
```

**Comment by pablokbs** [comment]
Gracias por el aporte, estoy armando un video de rbac (permisos en Kubernetes) donde voy a hablar de todo esto, salutes
