### ISSUE TITLE
problemas con Kubernetes

### ISSUE THREAD

**Issue by ChristopherHMelgar** [pablokbs/peladonerd#3]
Hola, como andas?

Continuo escribiéndote por acá, como recomendaste en uno de tus videos.

El ejemplo del video 1 de kubernates , lo pude levantar perfecto, pero cuando quiero usar una imagen propia (una app básica con express que muestra 'Hello World Docker!' ) es status del pod me tira ImagePullBackOff.

Le hice el describe al pod como me dijiste y me tiro error al hacer le pull (puede ser que este buscándolo en el repositorio de DockerHub y no lo encuentra por ese tira ese error?), tengo la imagen que quiero correr en pod en mi maquina, te adjunto las screenshot.
![describe](https://user-images.githubusercontent.com/33786947/56833803-f0977280-6845-11e9-82b6-8cec31321a78.png)
![images](https://user-images.githubusercontent.com/33786947/56833812-f725ea00-6845-11e9-9173-945fd304d2c1.png)

también el ReplicationController que modifiqué
![ReplicationController](https://user-images.githubusercontent.com/33786947/56834005-a367d080-6846-11e9-95be-481e508eb669.png)

Otra pregunta el ReplicationController se encarga de subir la imagen al servidor?

Gracias por todo de antemano, saludos!

**Comment by pablokbs** [comment]
Buenas! Gracias por crear el issue

Si, ya veo el problema, veo que la imagen la tenés en tu máquina (r2-d2) y el nodo de Kubernetes (que veo que está corriendo en digital ocean) no tiene la imagen. 

Tenés un error de concepto: el replication controller o el deployment solo se encarga de definir tu pod y descargar la imagen en el nodo desde internet. En este caso lo que tenés que hacer es subir tu imagen desde tu máquina a un repositorio y que después el RC se lo descargue en el nodo de digital ocean. 

La otra opción es que hagas un ssh al nodo y construyas la imagen en el nodo de Kubernetes. Después cuando apliques el manifiesto del RC, va a buscar la imagen localmente. Obvio que esto no es ideal ya que deberías pensar en tus nodos como máquinas descartables y no deberías ejecutar nada a mano en ellos. 

Mí recomendación es que te levantes un repositorio de imágenes de Docker en una instancia de digital ocean o que hostees tu imagen en dockerhub. Creo que podes hostear hasta un repositorio privado de forma gratuita en Dockerhub. 

Avísame si quedó claro o tenés alguna otra duda

**Comment by ChristopherHMelgar** [comment]
Buenas! Gracias por contestarme, 

Me quedo claro, subí mi imagen a dockerhub y la pude levantar sin problemas en el servidor, no me había dado cuenta de ese gran detalle por eso no me funcionaba, me has salvado! muchas gracias otra vez!.

Saludos, te veo en tu próximo vídeo.

**Comment by pablokbs** [comment]
Buenisimo, cierro el issue entonces
