### ISSUE TITLE
RSNAPSHOT 

### ISSUE THREAD

**Issue by franastor** [pablokbs/peladonerd#32]
Tengo asi el docker compose 
`  rsnapshot:
    container_name: bakups
    image: pablokbs/rsnapshot-cron
    restart: always
    volumes:
      - /etc:/host/etc:ro
      - /home/pi:/host/home/pi:ro
      - /media/pendrive/raspberrypi:/snapshots

    environment:
      - BACKUP_DIRECTORIES=/host/      raspberrypi/
      - CRON_DAILY=0 0 5 * * *
      - CRON_WEEKLY=0 0 6 * * 1
      - CRON_MONTHLY=0 30 6 1 * *
      - RSNAPSHOT_HOURLY_TIMES=0
      - RSNAPSHOT_DAILY_TIMES=7
      - RSNAPSHOT_WEEKLY_TIMES=4
      - RSNAPSHOT_MONTHLY_TIMES=3
`
y el log dice:

`----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot hourly 
----------------------------------------------------------------------------
ERROR: /etc/rsnapshot.conf on line 250:
ERROR: retain hourly 0 - "hourly" must be at least 1 or higher 
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in /etc/rsnapshot.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only tabs should be.
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot hourly 
----------------------------------------------------------------------------
ERROR: /etc/rsnapshot.conf on line 250:
ERROR: retain hourly 0 - "hourly" must be at least 1 or higher 
ERROR: ---------------------------------------------------------------------
ERROR: Errors were found in /etc/rsnapshot.conf,
ERROR: rsnapshot can not continue. If you think an entry looks right, make
ERROR: sure you don't have spaces where only tabs should be.
`
Si le pongo un valor superior a uno en RSNAPSHOT_HOURLY_TIMES=0 funciona.

**Comment by pablokbs** [comment]
Rarísimo, yo lo tengo EXACTAMENTE igual y me funciona, dame unos dias y lo pruebo bien

**Comment by franastor** [comment]
OK, simproblema.
Si encuentro la solucion antes te comento.
Muchisimas Gracias!!!

**Comment by franastor** [comment]
He vuelto a probar desde 0 y sigue dando error...ademas si le pongo que haga el de las horas...solo me hace ese...no hace ni diarios ni semanales...

**Comment by pablokbs** [comment]
Consulta, entre `/host/` y `raspberrypi/` tenes espacios o TABs? en el codigo de github parece que tenés espacios

**Comment by franastor** [comment]
efectivamente son espacion, si le meto tabs me dice esto al hacer el docker compose

ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yaml", line 90, column 34

**Comment by pablokbs** [comment]
Buenas noticias, pude reproducir el error, mas tarde lo arreglo y te aviso (o mañana temprano)

Paciencia

**Comment by pablokbs** [comment]
Lo arreglé. Hacé un `docker-compose pull rsnapshot && docker-compose up -d rsnapshot` y fijate si te anda

**Comment by franastor** [comment]
> + set -e
+ '[' rsnapshotd = rsnapshotd ']'
+ source /usr/bin/rsnapshot.d/rsnapshot.sh
++ set -e
++ cp /usr/bin/rsnapshot.d/rsnapshot.conf /etc/rsnapshot.conf
++ hourly_times=4
++ '[' -n 0 ']'
++ hourly_times=0
++ '[' 0 -gt 0 ']'
++ daily_times=7
++ '[' -n 7 ']'
++ daily_times=7
++ '[' 7 -gt 0 ']'
++ echo -e 'retain\tdaily\t7'
++ weekly_times=4
++ '[' -n 4 ']'
++ weekly_times=4
++ '[' 4 -gt 0 ']'
++ echo -e 'retain\tweekly\t4'
++ monthly_times=12
++ '[' -n 3 ']'
++ monthly_times=3
++ '[' 3 -gt 0 ']'
++ echo -e 'retain\tmonthly\t3'
++ syslogger_conf_tag=
++ '[' -n '' ']'
++ syslogger_conf_command=
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ backup_interval=hourly
++ '[' -n '' ']'
++ backup_dirs=
++ '[' -n '/host/      raspberrypi/' ']'
++ backup_dirs='/host/      raspberrypi/'
++ SAVEIFS=' 	
'
++ IFS=';'
++ for dir in $backup_dirs
+++ sed -e 's/ [ ]*/\t/g'
++ tab_dir='/host/	raspberrypi/'
++ echo -e 'backup\t/host/	raspberrypi/'
++ IFS=' 	
'
++ '[' -n '' ']'
+ cron_rsnapshot_hourly='0 20 * * * *'
+ '[' -n '' ']'
+ cron_rsnapshot_daily='0 30 1 * * *'
+ '[' -n '0 0 5 * * *' ']'
+ cron_rsnapshot_daily='0 0 5 * * *'
+ cron_rsnapshot_weekly='0 40 2 * * 5'
+ '[' -n '0 0 6 * * 1' ']'
+ cron_rsnapshot_weekly='0 0 6 * * 1'
+ cron_rsnapshot_monthly='0 50 4 1 * *'
+ '[' -n '0 30 6 1 * *' ']'
+ cron_rsnapshot_monthly='0 30 6 1 * *'
+ configfile=/root/.jobber
+ '[' '!' -f /root/.jobber ']'
+ touch /root/.jobber
+ cat
+ '[' 0 -gt 0 ']'
+ '[' 7 -gt 0 ']'
+ cat
+ '[' 4 -gt 0 ']'
+ cat
+ '[' 3 -gt 0 ']'
+ cat
+ cat /root/.jobber
---
- name: Daily
  cmd: /usr/bin/rsnapshot daily
  time: '0 0 5 * * *'
  onError: Continue
  notifyOnError: false
  notifyOnFailure: false

- name: Weekly
  cmd: /usr/bin/rsnapshot weekly
  time: '0 0 6 * * 1'
  onError: Continue
  notifyOnError: false
  notifyOnFailure: false

- name: Monthly
  cmd: /usr/bin/rsnapshot monthly
  time: '0 30 6 1 * *'
  onError: Continue
  notifyOnError: false
  notifyOnFailure: false

+ exec jobberd
Launching.
Loaded 3 new jobs for root.
Loaded 0 new jobs for bin.
Loaded 0 new jobs for daemon.
Loaded 0 new jobs for adm.
Loaded 0 new jobs for lp.
Loaded 0 new jobs for sync.
Loaded 0 new jobs for shutdown.
Loaded 0 new jobs for halt.
Loaded 0 new jobs for mail.
Loaded 0 new jobs for news.
Loaded 0 new jobs for uucp.
Loaded 0 new jobs for operator.
Loaded 0 new jobs for man.
Loaded 0 new jobs for postmaster.
Loaded 0 new jobs for cron.
Loaded 0 new jobs for ftp.
Failed to load jobs for open /dev/null/.jobber: not a directory: sshd
Loaded 0 new jobs for at.
Loaded 0 new jobs for squid.
Loaded 0 new jobs for xfs.
Loaded 0 new jobs for games.
Loaded 0 new jobs for postgres.
Loaded 0 new jobs for cyrus.
Loaded 0 new jobs for vpopmail.
Loaded 0 new jobs for ntp.
Loaded 0 new jobs for smmsp.
Failed to load jobs for open /dev/null/.jobber: not a directory: guest
Loaded 0 new jobs for nobody.
Loaded 0 new jobs for abc.
Loaded 0 new jobs for jobber_client.
totalJobs: 1; len(m.jobs): 3
New context: 0.0
Main thread context: 0.0
New context: 0.0.0

>

**Comment by franastor** [comment]
Ahora tiene pinta que ha funcionado, el log me dice todo esto...vamos a ver si todo va ok!!! muchisimas gracias y te voy comentando...

**Comment by pablokbs** [comment]
Buenisimo, lo cierro y cualquier cosa lo volvés a abrir. Saludos

**Comment by nedxus-5** [comment]
Hola Pablokbs no consigo ejecutar el docker en una maquina con la arquitectura amd64 me indica el error al configurar el parametro hourly o en su caso error 211 que creo que es referido a la arquitectura te paso los errores y comando que utilizo para montar contenedor
docker-compose -f docker-compose.yml up

"rsnapshot_1  | standard_init_linux.go:211: exec user process caused "exec format error"

Cuando ejecuto el comando indicado:
 "docker-compose pull rsnapshot && docker-compose up -d rsnapshot"
Respuesta:
Docker/rsnapshot/amd64# docker-compose logs -f --tail=10
Attaching to amd64_rsnapshot_1
rsnapshot_1  | standard_init_linux.go:211: exec user process caused "exec format error"
amd64_rsnapshot_1 exited with code 1

, tambien indicarte que lo tengo funcionando correctamente un una Rpi4, saludos.

**Comment by pablokbs** [comment]
Claro eso es porque el contenedor está hecho para arquitecturas ARM, tendrías que buscar uno para amd64, seguro hay

**Comment by nedxus-5** [comment]
muchas gracias .... nos vemos en el canal ....
