### ISSUE TITLE
Openvpn + pihole

### ISSUE THREAD

**Issue by mariooc** [pablokbs/peladonerd#33]
Hola Pablo
estuve mirando tu vídeo de openvpn y le quise agregar pihole
el problema es que no sé como decirle a ovpn la ip del pihole como DNS en ovpn

**Comment by mariooc** [comment]
Buenas noches,
lo hice andar, pero no me gusta la manera
le hice un `docker inspect pihole | grep -i ipaddress"` copie la ip  y  la pegue en `openvpn-data/conf/openvpn.conf`
cual sería la manera mas prolija de hacerlo ? 

estuve mirando [este tutorial](https://demyx.sh/tutorial/how-to-run-openvpn-and-pi-hole-using-docker-in-a-vps/)
pero despues de X minutos pihole.dominio.com retorana `Gategay timeout`

**Comment by pablokbs** [comment]
Hola no entendi que querés hacer, podrías explicar qué problema querés resolver?

**Comment by cabedev** [comment]
Buenas, 

yo también estoy interesado en este tema, mi necesidad seria que cuando se conecte un usuario por openvpn navegue en internet con pi-hole activo. 

He comprobado que la configuración por defecto del contenedor de openvpn utiliza las dns de google.
¿Como enlazar o modificar openvpn para que el trafico de salida pase por pi-hole y cuando utilicemos la vpn podamos navegar en internet sin publicidad?

gracias por valiosa formación, un saludo

**Comment by alcar21** [comment]
Buenas,
Al servidor de VPN hay que asignar la DNS de pihole. Yo lo uso en local y
funciona muy bien aunque se fue un día la luz y no funciona bien, ya lo
miraré.

Las DNS que usa pihole puedes elegir de los proveedores que trae, google,
Cloudflare, etc... Esos los usa el internamente para resolver y cachear las
direcciones.

Espero que te sirva de ayuda.

**Comment by pablokbs** [comment]
Ok voy a ver si puedo hacer un video de openvpn + pihole :+1:

**Comment by cabedev** [comment]
Buenos días, 

encontré alguien que lo hizo en https://github.com/mr-bolle/docker-openvpn-pihole
pero me gustaría una versión tuya que seria más sencilla. 

Yo lo quiero usar de dos formas, para la red local usar pi-hole sin vpn indicando la ip en el dhcp del router (en uso) y cuando conecto desde el exterior por vpn que se utilice pi-hole.

un saludo, magnificos videos y nos vemos en la red
