### ISSUE TITLE
Typo en ejemplo de traefik

### ISSUE THREAD

**Issue by josefigueredo** [pablokbs/peladonerd#35]
En el ejemplo de traefik, no levanta docker-compose. Solo le faltan 4 espacios al inicio de la linea 26 del archivo:

`https://github.com/pablokbs/peladonerd/blob/master/varios/2/docker-compose.yaml`

Gracias por el ejemplo !

**Comment by pablokbs** [comment]
Podés hacer un PR y lo mergeamos?

**Comment by pablokbs** [comment]
Esto lo arreglaron acá: https://github.com/pablokbs/peladonerd/commit/01c800f57b9f1ae94088a13470e08da762131008
