### ISSUE TITLE
Falla: Internal server error  con poste.io y traefik en digitalocean.

### ISSUE THREAD

**Issue by fradducho** [pablokbs/peladonerd#38]
Buenas,

Muchas gracias por tus videos.

Estuve intentando montar  poste.io y traefik en un servidor de digital ocean pero me falla cuando intento ir  al mailserver.

He montado otro contenedor "whoami" por ejemplo y he puesto un host domain y  funciona correctamente por lo que descarto completamente que traefik este mal.

Lo que me ocurre es que me da un "Internal server error"

Aqui dejo mi docker-compose.yaml a ver. :+1: 

[https://raw.githubusercontent.com/fradducho/fraddygil/master/docker-compose.yaml](https://raw.githubusercontent.com/fradducho/fraddygil/master/docker-compose.yaml)

He comentado el whoami y el contenedor my-app  que fueron de pruebas para poder enfocarme unicamente en el del mail pero me falla.

Puede mas o menos iluminarme que puede estar pasando ?

Se que has colocado unos videos donde lo haces con nginx pero me interesa hacerlo con traefik. Que si no hay manera entonces lo hago con nginx pero dejo este issue  aqui a ver si alguno de ustedes puede ayudarme.

Mil gracias de ante mano.

**Comment by pablokbs** [comment]
Hola! podrias hacer un tail a los logs de traefik e intentar visitar el sitio? Capaz ahi vamos a poder ver el error

Saludos

**Comment by fradducho** [comment]
Buenas, Noches aqui esta .

traefik      | time="2019-10-12T05:29:02Z" level=debug msg="'500 Internal Server Error' caused by: net/http: HTTP/1.x transport connection broken: malformed HTTP status code \"1072e6c94027\""
traefik      | time="2019-10-12T05:29:02Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en-US,en;q=0.9\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36\"],\"X-Forwarded-Host\":[\"mail.fraddygil.com\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"7145063cfa1b\"],\"X-Real-Ip\":[\"10.100.1.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"mail.fraddygil.com\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.100.1.1:57566\",\"RequestURI\":\"/\",\"TLS\":null}"

**Comment by pablokbs** [comment]
Me parece que el problema es que en mail tenes al mismo tiempo `HTTPS=off` y una label que dice `"traefik.http.routers.mail.entrypoints=websecure"` entonces traefik está intentando conectarse a poste usando TLS, y vos lo tenes desactivado, deberias cambiar esa label a : `"traefik.http.routers.mail.entrypoints=web"`

**Comment by fradducho** [comment]
Hola nuevamente,

He intentado hacer esos cambios que recomiendas pero sin exito. Me lanza el mismo error.

**Comment by pablokbs** [comment]
Lo que deberias hacer es un exec al contenedor de traefik y revisar la configuracion generada de nginx. Una vez ahi, deberias probar hacer curl desde traefik a poste, a ver si te funciona

**Comment by joseantoniocampillo** [comment]
Hola. Me gustaría montar poste lo con docker y traefik. Conseguiste arreglarlo?
Tengo dos máquinas sirviendo con traefik. Y siempre me cree una red de docker particular para sus servicios. Por tanto no bindeo los puertos (con 'ports') en docker-compose; sólo lo expongo a la red que atiende traefik (con 'expose'). 
Podrías intentarlo de esa forma?
Lo solucionaste de algún modo?
Gracias 🙋

**Comment by ChristianBarrientos** [comment]
Hola, estoy en la misma. me gustaria meter a poste.io en el cluster de kubernetes (q lo tengo con traefik) alguna sugerencia?

**Comment by Zakspeed** [comment]
este es mi docker-compose del poste.

me carga el interface gráfico
aun no se si funciona correctamente pero esta "levantado"

uso Traefik 2.2X

```
  poste:                                                                                                                                                                    image: analogic/poste.io                                                                                                                                                restart: always                                                                                                                                                     #    network_mode: "host"                                                                                                                                                   ports:                                                                                                                                                                    - 25:25                                                                                                                                                                 - 888:80                                                                                                                                                                - 4433:443
      - 110:110
      - 143:143                                                                                                                                                               
      - 465:465
      - 587:587
      - 993:993
      - 995:995
    volumes:
      - ./maildata:/data                                                                                                                                                    environment:                                                                                                                                                              - HTTPS=OFF                # cambie esto!!!                                                                                                                                       #      - HTTP_PORT=888                                                                                                                                                  #      - HTTPS_PORT=4433                                                                                                                                                      - DISABLE_CLAMAV=TRUE                                                                                                                                             #      - HOSTNAME=mail.example.com                                                                                                                                            - TZ=Europe/Madrid                                                                                                                                                                                                                                                                                                                            labels:                                                                                                                                                            $      - "traefik.enable=true"                                                                                                                                                 - "traefik.http.routers.mail.rule=Host(`mail.EJEMPLO.com`)"                                                                                                              - "traefik.http.routers.mail.entrypoints=web"                                                                                                                           - "traefik.http.routers.mail.middlewares=http-a-https"                                                                                                                                                                                                                                                                                          - "traefik.http.routers.mail-https.rule=Host(`mail.EJEMPLO.com`)"                                                                                                        - "traefik.http.routers.mail-https.entrypoints=websecure"                                                                                                               - "traefik.http.routers.mail-https.tls.certresolver=myresolver"                                                                                                         - "traefik.http.services.mail-https.loadbalancer.server.port=80"
```
