### ISSUE TITLE
duda correo poste.io

### ISSUE THREAD

**Issue by PinoVanDyk** [pablokbs/peladonerd#39]
Hola Pelado Nerd vi tu video CREÁ UN SERVER DE CORREO EN 1 MINUTO / V2M: Poste me pareció muy interesante el ver que tan rápido se configura un servidor de correo, yo tengo uno instalado en la empresa donde laboro pero ahora me estoy encontrando con un problema de que los correos no llegan al destinatario y no encuentra gran información no se si tu puedas auxiliarme, entre al  SMTP Banner Check desglosan dome lo siguiente 

> `

> El banner SMTP emitido por su servidor de correo electrónico no contenía el nombre de host que resolvimos para la dirección IP de su servidor.

`

 dentro del dashboard veo esto en la sección de Diagnostico de conexión del servidor  la siguiente información y no se si es correcto o debería de tener mi dominio 

  | Test | Description | Test result
 Testing gmail.com port 25 connection | Received "220 mx.google.com ESMTP t3si2340130qtq.156 - gsmtp"

esperando contar con tu iluminación quedo atento a cualquier duda

**Comment by pablokbs** [comment]
Hola, gracias por los comentarios!

> El banner SMTP emitido por su servidor de correo electrónico no contenía el nombre de host que resolvimos para la dirección IP de su servidor.

Fijate de configurar el mismo hostname en poste del dominio (y subdominio) que estés usando

**Comment by PinoVanDyk** [comment]
ok voy a checar eso, muchas gracias por la iluminación

**Comment by Allyogi873** [comment]
> pudiste corregir el error?
