### ISSUE TITLE
Duda sobre puertos en Docker

### ISSUE THREAD

**Issue by mariooc** [pablokbs/peladonerd#4]
Hola Pablo
Uso ufw como firewall
la pregunta es por que si hago binding de un puerto con docker, no pasa por el firewall ? 

ejemplo:
tengo bloqueado el puerto 9700 en ufw, pero si hago el binding del contenedor de jenkins  
puedo acceder desde el browser `my-host:9700`

Hay manera de cambiar esto? o sea que todo pase por ufw?

**Comment by pablokbs** [comment]
Buenas

Esto es porque el servicio de docker tiene los permisos para agregar o quitar reglas iptables, modificando las reglas que ufw crea, esto se puede desactivar modificando el `/etc/default/docker` (o similar dependiendo de la distro) y agregando esta linea:

```
DOCKER_OPTS="--iptables=false"
```

Despues de eso tenes que reiniciar el servicio de Docker o reiniciar. De esta forma le estas diciendo al servicio de Docker que no modifique reglas iptables.

[Acá tenes mas info](https://www.techrepublic.com/article/how-to-fix-the-docker-and-ufw-security-flaw/)
