### ISSUE TITLE
Poste.io MAILER-DAEMON@<mydomain.com>: Message not delivered

### ISSUE THREAD

**Issue by DylanPozuelo93** [pablokbs/peladonerd#40]
Saludos estimados PeladoNerd y comunidad. Me gustó el video de "CREÁ UN SERVER DE CORREO EN 1 MINUTO / V2M: Poste" y agradezco se compartiera esa información. Actualmente tengo un problema, del cual agradecería ayuda, y que consta de que configuré una droplet con docker y poster.io y a la hora de enviar un mensaje me aparece un error como el siguiente: 
message not delivered
A problem has occurred when trying to deliver your mail to ...
Error: 550 5.7.1 this message does not have authentication information or fails to pass authentication checks. To best protect our users from spam&undefined; the message has been blocked. please visit https://support.google.com/mail/answer/81126#authentication for more information.
solo me deja enviar y recibir mails de mi propio dominio.... los demas, salientes, terminan rebotando. Solicito ayuda para saber que me hace falta configurar.

Actualmente tengo configurados un record MX manejado por mail.<mi-dominio> apuntando a la droplet con docker+poste.io y los demas records A apuntando a la droplet con mi sitio web.

**Comment by DylanPozuelo93** [comment]
Saludos. quería comentarles que ya resolví. El problema se debia al record PTR el cual se configura automáticamente en DigitalOcean con el nombre del droplet; yo estaba usando una ip flotante, y lastimosamente DigitalOcean no tiene la caracteristica de configurar manualmente un record PTR a una ip flotante; por tanto la solución fue eliminar la ip flotante y actualizar el record A del dominio a la ip directa de la droplet. ahora solo queda el problema de que los correos llegan al destinatario como SPAM en las cuentas de outlook (en gmail me funcionan perfecto)

**Comment by pablokbs** [comment]
Buenisimo que lo hayas resuelto, y perdón por la demora, he estado a full.

Con respecto al spam, es probable que la IP de tu instancia de DO esté en una lista negra, hay paginas como mxtoolbox.com que te muestran esa info y te dan los links para sacarte de esas listas.

Suerte!
