### ISSUE TITLE
colas y sockets en clusters

### ISSUE THREAD

**Issue by juancho637** [pablokbs/peladonerd#43]
Hola Pablo, tengo unas preguntas:

1. Ya que es primera vez que voy a implementar colas en cluster, teniendo en cuenta que en cada pod esta la misma aplicación y tengo un servidor redis aparte, tendría que tener en cada pod ejecutando a Supervisor el comando para la ejecución de las colas que se encuentran en redis?

2. Ya que me encuentro desarrollando la aplicación en Laravel(PHP), este para poder tener ciertas partes en tiempo real se conecta con un servidor Node.js para la parte de sockets, eso quiere decir que tengo que crear otros pods para la ejecución de este servidor teniendo en cuenta de que los canales también vienen de redis. estaría bien dejarlo bajo el mismo dominio o recomiendas colocarlos bajo otro o un subdominio del primero?

Muchas gracias.

**Comment by pablokbs** [comment]
Hola

1. No entendí a qué te referís con "el comando para la ejecución de las colas en redis"
2. Yo los separaría solo para que el navegador los baje en paralelo y vaya más rápido, pero la verdad que no creo que haya mucha diferencia, así que lo podés poner todo bajo el mismo dominio.

**Comment by juancho637** [comment]
1. Por ejemplo en laravel uno tiene que ejecutar el siguiente comando para hacer que las colas sean ejecutadas: `php artisan queue:work --tries=3` entonces eso quiere decir que en cada pod se estaría ejecutando este comando, ósea que cada pod estaría a la escucha de que se inserte un nuevo trabajo a la cola, y no se si esto este bien

**Comment by pablokbs** [comment]
Idealmente deberias usar algun sistema de lock, para que no haya colisión entre los pods, seguramente laravel tiene alguna forma de hacer eso
