### ISSUE TITLE
No consigo enviar mail con poste.io

### ISSUE THREAD

**Issue by aratar79** [pablokbs/peladonerd#45]
Hola chic@s, no se si tiene algo que ver con el dkim, pero no consigo enviar ni un solo mail con poste.io, donde configuro la clave privada dkim, dentro del contenedor o en el host?. Busco documentación y no la encuentro, alguna sugerencia? gracias, un saludo

**Comment by pablokbs** [comment]
La clave DKIM la podes subir en Virtual Domains -> tudominio -> DKIM Key

**Comment by aratar79** [comment]
Gracias Pablo, estuve mirando el otro issue sobre Spam, ya configuré el
dkim spf dmarc pero no hay manera de que me lleguen los mails a ninguna
parte, ni si quiera al spam, no sé, se te ocurre algo.

Muchas gracias de antemano y te lo tengo que decir, gran contenido en tu
canal, no decaigas porque esta buenisimo!

**Comment by pablokbs** [comment]
Y hay que ver los logs, fijate en delivery queue a ver si tenes algun error o algo que te los esté frenando

**Comment by aratar79** [comment]
Siento molestar pero no consigo hacerlo funcionar, en delivery en el web
admin no hay nada, conseguí ver el log haciendo un docker exec bash al
contenedor, adjunto el log a ver si tu ves algo, probé con dos dominios
diferentes de diferentes proveedores, mxtoolboox solo me tira 2 warnings
pero no llega el correo a ningún sitio. Muchas gracias, un saludo.
[image: logs.PNG]

**Comment by pablokbs** [comment]
No veo el adjunto, fijate de subirlo desde github y no desde el mail

**Comment by aratar79** [comment]
Perdona lo puse como imagen, una captura de pantalla, adjunto el archivo
entero.


Muchas, muchas gracias!

**Comment by pablokbs** [comment]
No respondas con el adjunto desde el mail porque no se sube. Hacelo desde la página o subilo a otro lado y pone el link

**Comment by aratar79** [comment]
ahí lo subo sorry! 
[2020-01-06-total.log](https://github.com/pablokbs/peladonerd/files/4032007/2020-01-06-total.log)

**Comment by pablokbs** [comment]
Parece que faltan mas logs, habria que ver los logs del queue

**Comment by aratar79** [comment]
Sorry pero no encuentro los logs del queue, Mando todos los de la carpeta delivery?

**Comment by aratar79** [comment]
adjutno los logs de queue, mil gracias.
[queue.zip](https://github.com/pablokbs/peladonerd/files/4035892/queue.zip)

**Comment by aratar79** [comment]
Puede ser un problema de permisos, acabo de borrar los volumenes y volver a
levantar el servidor y veo que no me crea el directorio etc/nginx/certs/
midominio.com, crees que podría ser un problema de permisos en el
directorio, que permisos y propietario tendría que tener ese volumen?

Mil gracias de nuevo

**Comment by aratar79** [comment]
Bueno al final lo conseguí, parece raro, a ver si alguien sabe que puede ser, la primera vez que lo monte fue con el docker-compose que sale en la documentación de poste.io en el apartado FAQS con un dominio comprado en abansys(españa) y un vps en clouding.io(españa), después de darle muchas vueltas, compre otro dominio en arsys(españa) y levante un droplet(vps) en digitalocean(Alemania) exactamente con la misma configuración en todos lados, mismos registros DNS, mismo firewall, mismos sistema operativo, todo exactamente igual, en el segundo funciona y en el primero no. la configuración no la cuelgo porque es exactamente la que dice en la documentación de poste.io. Alguien sabría decirme por que????

**Comment by pablokbs** [comment]
Muy raro, la única que se me ocurre es que el dominio esté en una lista negra? Es muy raro eso

**Comment by cocodrino** [comment]
Hola @pablokbs , gracias por el video de poste.io...tengo una pregunta con el dkim...al generar el key dentro de poste.io me sale algo como esto

```
s20200831157._domainkey.<midominio>.com. IN TXT "k=rsa; p=MIIBIxxxxxxxxPqgbZL+dJafOqMl4+HoqwIDAQAB"
```

ahora...cómo debo agregar ese registro en mi DNS?
sería un registro txt con el subdominio s20200831157._domainkey  y la clave (la resumí con xxxxx porque es larguisima "k=rsa; p=MIIBIxxxxxxxxPqgbZL+dJafOqMl4+HoqwIDAQAB"

esas comillas las debo colocar en el registro o no?

mil gracias pelado!

**Comment by pablokbs** [comment]
Correcto, las comillas creo que no hacen falta (y no hacen la diferencia)

**Comment by cocodrino** [comment]
gracias Pablo, crack!

**Comment by snaven10** [comment]
quien me pude ayudar no consigo mandar correos si los puedo recibir lo tengo en el mismo droplets donde pienso poner mi página web tengo el analogic/poste.io que es la image de Docker para el servidor de correos ya cuelgo las configuraciones del nginx server de correos 

server de corroes
`services:
  poste:
    image: analogic/poste.io
    restart: always
    hostname: mail
    ports:
      - 25:25
      - 81:80
      - 110:110
      - 143:143
      - 8443:443
      - 465:465
      - 587:587
      - 993:993
      - 995:995
    volumes:
      - /root/mail-data:/data
    environment:
      - HTTPS=OFF
      - DISABLE_CLAMAV=TRUEl`

Configuracion de nginx para el servidor para mi pagina web dominio principal
`server {

        root /var/www/samuelfunes.com/html;
        index index.html index.htm index.nginx-debian.html;

        server_name samuelfunes.com www.samuelfunes.com;

        location / {
                try_files $uri $uri/ =404;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/samuelfunes.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/samuelfunes.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.samuelfunes.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = samuelfunes.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        listen [::]:80;
        server_name samuelfunes.com www.samuelfunes.com;
    return 404; # managed by Certbot

}`
Configuracion de nginx para servidor correos la config del sub dominio 
`upstream mail {
    server 0.0.0.0:81 weight=1 fail_timeout=0;
}

server {
    server_name mail.samuelfunes.com www.mail.samuelfunes.com;

    #Access log
    access_log /var/log/nginx/odoo-access.log;

    #general proxy settings
    #force timeouts if the backend dies
    proxy_connect_timeout 120s;
    proxy_send_timeout 120s;
    proxy_read_timeout 120s;
    send_timeout 120;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    #set headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;

    #by default, do not forward anything
    proxy_redirect off;
    proxy_buffering off;

    location / {
        proxy_pass http://mail;
        #proxy_pass http://172.21.0.2:80;
        #proxy_pass https://172.21.0.2:443;
    }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mail.samuelfunes.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mail.samuelfunes.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = www.mail.samuelfunes.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = mail.samuelfunes.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        listen 80;
        listen [::]:80;

        server_name mail.samuelfunes.com www.mail.samuelfunes.com;
    return 404; # managed by Certbot
}`

**Comment by ManuelManriquez** [comment]
Hola Pablo, recientemente comencé a realizar este tutorial y tengo el problema de que los correos se quedan atorados en el Delivery Queue.
Estuve leyendo todo el issue y al parecer no se llegó a una solución tal cual. Estos son mis logs
[logs.txt](https://github.com/pablokbs/peladonerd/files/11434596/logs.txt)
