### ISSUE TITLE
Dashboard poste.io

### ISSUE THREAD

**Issue by PinoVanDyk** [pablokbs/peladonerd#46]
Hola buen dia peladoNerd, quisiera pedir de tu ayuda si es posible que me puedas decir que significa esto que estoy viendo constantemente en mi dashboard de poste.io

B9-9E1D-FBF0E48DB27C... | ip-113-131.4vendeta.com / 78.128.113.131 → 465 | helo: ip-113-131.4vendeta.com. auth: auth/poste/LOGIN local_port: disconnected
-- | -- | --
21-ACDB-9E186D1955A 0217.ip-51-91-99.eu / 51.91.99.217 → 587 | helo: ADMIN local_port: disconnected
he tratado de indagar en internet pero no he encontrado mucha informacion podrias apoyarme, de antemano muchas gracias Saludos desde Mexico

**Comment by pablokbs** [comment]
Hola, la verdad nunca he visto ese error y no encuentro nada en la documentacióin de ellos. Tal vez podrias crear un ticket en el repo de ellos:

https://bitbucket.org/analogic/mailserver/issues
