### ISSUE TITLE
Registry UI 

### ISSUE THREAD

**Issue by ShankyJS** [pablokbs/peladonerd#48]
Hola Pablo, tenía una pequeña consulta, veo que cuando levantamos el docker-compose este lleva la clave ya hardcodeada en el mismo. 

Y por ende al ingresar a la UI siempre estoy autorizado, es posible cambiar esto para que haga un prompt de la password?

saludos.

**Comment by pablokbs** [comment]
Hola, deberias probar agregando autenticación basica usando la doc del proxy, fijate acá:

https://github.com/jwilder/nginx-proxy#basic-authentication-support

Parece que tenes que crear un archivo en `/etc/nginx/htpasswd/$VIRTUAL:HOST` y nginx lo va a cargar solo, probalo!

**Comment by ShankyJS** [comment]
Ok, voy a probar. Mil gracias!
