### ISSUE TITLE
Duda sobre Terraform

### ISSUE THREAD

**Issue by cmastro** [pablokbs/peladonerd#5]
Buenas Pelado!!!

Estoy arrancando con Terraform y quería consultar si es posible usar Terraform (obviamente) con servidores que no esten entre los providers.. como por ejemplo "Terraformear" en una Raspberry.

**Comment by pablokbs** [comment]
Si claro, aunque la idea de terraform es mas que nada crear infraestructura, también podes instalar paquetes y cosas usando terraform y modulos como el de `remote-exec`:

https://www.terraform.io/docs/provisioners/remote-exec.html

Checkealo
