### ISSUE TITLE
No puedo levantar el container de configmap-reload del alertmanager

### ISSUE THREAD

**Issue by kevinszuchet** [pablokbs/peladonerd#54]
Buenas, primero que nada quería agradecerte un montón por todo el contenido que compartis en tu video. Estoy teniendo un problema cuando quiero levantar el deployment del alertmanager para notificar via slack (tratando de seguir al pie de la letra tu clase 7 de Kubernetes).

Al principio no podía levantar el PVC porque me decía que __no encontraba el storageclass.storage.k8s.io standard__. Saque la línea de storageClassName del yaml del pvc para que use el default de mi cluster (o eso entendí que hacía) y logre crear el volumen.
Ahora el problema está en que hay uno de los containers del alert manager (el del configmap-reload) que no puede levantar debido a este error:
``` sh
Error: failed to start container "prometheus-alertmanager-configmap-reload": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"10485760\\\\\\\" to \\\\\\\"/sys/fs/cgroup/memory/kubepods/pod5d900e7d-627d-4622-a729-a055245697ba/prometheus-alertmanager-configmap-reload/memory.limit_in_bytes\\\\\\\": write /sys/fs/cgroup/memory/kubepods/pod5d900e7d-627d-4622-a729-a055245697ba/prometheus-alertmanager-configmap-reload/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
```
Esto sólo me sucede utilizando minikube. Si gasto los dolares que nos regalaste en digital ocean ahi funciona correctamente.
Se te ocurre que puedo hacer para solucionarlo?
Estuve viendo este [issue](https://github.com/opencontainers/runc/issues/1740) para tratar de entender el problema.

Estoy usando:
- minikube v1.7.3
- kubctl v1.17.3
- docker: v19.03.6

**Comment by pablokbs** [comment]
Parece que tenes algun problema con tu maquina de minikube, yo probaria reiniciarla o recrearla, te fijaste si tenés la ultima version?

**Comment by kevinszuchet** [comment]
Si tengo la última que me la baje hace un par de días para usarla con tus videos. Probe reiniciando y sigue mostrando el mismo error. Igualmente pude levantar todo correctamente en el cluster de digital ocean
