### ISSUE TITLE
poste.io error al enviar correo desde laravel

### ISSUE THREAD

**Issue by geyssonvidal** [pablokbs/peladonerd#58]
hola tengo un servidor con poste.io para los correos  y otro con laravel trate de configurar para enviar correos desde la web creada con laravel usando el servidor con poste. io pero me sale el siguiente error: ( Connection could not be established with host smtp.dominio.com :stream_socket_client(): Peer certificate CN=`mail.noumbu.com' did not match expected CN=`smtp.dominio.com') 
ante usaba el smtp de gmail y funcionaba pero ahora que tenia un servidor de correo propio quise cambiarlo para que los correos salgan con mi dominio y no con gmail y  no estar pagando a google
agradezco su ayuda y respuesta

**Comment by pablokbs** [comment]
Hola! Parece que el certificado no tiene el dominio que estas usando, cambiaste `smtp.dominio.com` ?
