### ISSUE TITLE
No funciona Docker Sock Raspberry Pi

### ISSUE THREAD

**Issue by mauser1909** [pablokbs/peladonerd#6]
Hola Pablo, te cuento mi problema, no me está funcionando el re direccionamiento de sock con NGINX-PROXY y Virtual Host en ARM. Me muestra el index del proxy.
$ curl http://raspi1909.hopto.org/

docker-compose.yml
nginx-proxy:
  image: lroguet/rpi-nginx-proxy:latest
  restart: always
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

www:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - /home/pi/docker/nginx/html:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=raspi1909.hopto.org

LOGS
pi@raspi1909:~/docker $ docker-compose logs -f
Attaching to docker_nginx-proxy_1, docker_www_1
nginx-proxy_1  | 185.124.173.205 - - [17/May/2019:14:49:06 +0000] "GET / HTTP/1.1" 200 867 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
nginx-proxy_1  | 200.125.69.42 - - [17/May/2019:15:08:56 +0000] "GET / HTTP/1.1" 200 867 "-" "curl/7.52.1"
nginx-proxy_1  | 200.125.69.42 - - [17/May/2019:15:21:14 +0000] "GET / HTTP/1.1" 200 867 "-" "curl/7.52.1"

**Comment by pablokbs** [comment]
Buenas, podes mostrar el contenido de tu directorio `/home/pi/docker/nginx/html` ?

**Comment by mauser1909** [comment]
Hola, te paso:
pi@raspi1909:~/docker/nginx/html $ pwd
/home/pi/docker/nginx/html
pi@raspi1909:~/docker/nginx/html $ ls
index.html
pi@raspi1909:~/docker/nginx/html $ ls -al
total 12
drwxr-xr-x 2 root root 4096 May 17 08:55 .
drwxr-xr-x 4 root root 4096 May 17 09:01 ..
-rw-r--r-- 1 root root 1101 May 17 08:55 index.html
pi@raspi1909:~/docker/nginx/html $

**Comment by pablokbs** [comment]
Ok la pagina está bien, hacé un curl a tu pagina:

`curl http://raspi1909.hopto.org/index.html`

Y mostrame los logs, quiero ver cual contenedor muestra el 404

**Comment by mauser1909** [comment]
Attaching to docker_nginx-proxy_1, docker_www_1
 curl http://raspi1909.hopto.org
nginx-proxy_1  | 200.125.69.42 - - [17/May/2019:15:59:58 +0000] "GET /
HTTP/1.1" 200 867 "-" "curl/7.52.1"
curl http://raspi1909.hopto.org/index.html
nginx-proxy_1  | 200.125.69.42 - - [17/May/2019:16:00:06 +0000] "GET
/index.html HTTP/1.1" 404 168 "-" "curl/7.52.1"

**Comment by pablokbs** [comment]
Ah, estoy viendo que estás usando otra imagen para el nginx-proxy diferente a la que yo recomendé:

`image: lroguet/rpi-nginx-proxy:latest`

Probá cambiando a:

`image: jwilder/nginx-proxy`

Y ahí te va a andar

**Comment by mauser1909** [comment]
Pablo, no le gusta.

Attaching to docker_nginx-proxy_1, docker_www_1
nginx-proxy_1  | standard_init_linux.go:207: exec user process caused "exec
format error"
nginx-proxy_1  | standard_init_linux.go:207: exec user process caused "exec
format error"
nginx-proxy_1  | standard_init_linux.go:207: exec user process caused "exec
format error"
nginx-proxy_1  | standard_init_linux.go:207: exec user process caused "exec
format error"
nginx-proxy_1  | standard_init_linux.go:207: exec user process caused "exec
format error"
nginx-proxy_1  | standard_init_linux.go:207: exec user process caused "exec
format error"
nginx-proxy_1  | standard_init_linux.go:207: exec user process caused "exec
format error"
docker_nginx-proxy_1 exited with code 1
Lo voy a probar con una droplet de Digital Ocean.

Gracias Pablo, abrazo.

PD: Si podes probalo en una ARN.

**Comment by pablokbs** [comment]
Ah bien, probaste este? `jockebr/jwilder-nginx-proxy-arm32v7`

**Comment by mauser1909** [comment]
Pablo, ahora pruebo esa imagen.
https://dockerproxy.hopto.org/ con droplet me funciona OK.

**Comment by mauser1909** [comment]
Pablo, con esa imgen me da este error:

pi@raspi1909:~/docker $ docker-compose logs -f
Attaching to docker_nginx-proxy_1, docker_www_1
nginx-proxy_1  | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A
pre-generated dhparam.pem will be used for now while a new one
nginx-proxy_1  | is being generated in the background.  Once the new
dhparam.pem is in place, nginx will be reloaded.
nginx-proxy_1  | /app/docker-entrypoint.sh: line 33: /usr/local/bin/forego:
cannot execute binary file: Exec format error
nginx-proxy_1  | /app/docker-entrypoint.sh: line 33: /usr/local/bin/forego:
Success

Abrazo.

**Comment by pablokbs** [comment]
Ag, esa es la imagen que te pasé? que raro que te tire error de formato, cual raspberry tenes?

**Comment by mauser1909** [comment]
Hola, tengo una 3 B+.

**Comment by Lli-li** [comment]
Yo tuve que cambiar las dos imágenes para que funcionara en raspberry.
nginx-proxy:
    image: braingamer/nginx-proxy-arm
letsencrypt:
    image: keksnase/letsencrypt-nginx-proxy-companion-armhf
Y ya me genera los certificados en la carpeta, pero no me abre en https.

Espero que a alguien le ayude y nos oriente con lo del https.

**Comment by pablokbs** [comment]
@Lli-li tenes acceso externo a tu dominio por medio de http? let's encrypt tiene que poder llegar a tu contenedor por HTTP para poder generar el cert

**Comment by Lli-li** [comment]
Gracias Pelado, no era eso es que tenia los mismos errores de @mauser1909, pero yo suponia que era por el script, pero no, eran las imagenes que son de arquitectura 64bits y las Raspberry usan arm.

Modifique en mi ingenuidad al a version 2 del yml, pero eso no permitia que los volumenes convivieran holisticamente. Cuando cambie a la version 3 con las nuevas imagenes funciono bien.
g-lee.duckdns.org por si quieres ver mi super pagina.
