### ISSUE TITLE
Cambios en api 

### ISSUE THREAD

**Issue by rodrigo398** [pablokbs/peladonerd#60]
Estoy siguiendo algunos videos para crear cluster usando minikube, y varios archivos yaml que devuelven error de matcheo en versiones. Ej:

Video:
https://www.youtube.com/watch?v=Gp6LNymkw70

Archivo:
https://github.com/pablokbs/peladonerd/blob/master/kubernetes/13/04-mongo-full.yaml

Error:
`error: unable to recognize "04-mongo-full.yaml": no matches for kind "StatefulSet" in version "apps/v1beta1"`

Siguiendo otros videos, tambien recibi un error parecido (ahora no me acuerdo cual es), pero fue algo parecido como esto: 

`no matches for kind "DaemonSet" in version "extensions/v1beta1"`

Por lo poco que puedo entender, hay sintaxis que están deprecadas, pero no entiendo bien cual o como reemplazarlas. 

Esta es mi version de kubectl
`
 rodrix@rodrix  ~  kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
`

Alguien mas tuvo el mismo problema?, 

Gracias.

**Comment by rodrigo398** [comment]
Encontre la forma de cambiar de version usando convert:

`
kubectl convert -f 04-mongo-full.yaml --output-version apps/v1 > test.yaml
`

Consulta @pablokbs :

1_ Esta bien seguir esta practica de convertir?
2_ Existe alguna herramienta online (o no) para crear mis yaml con esa versión? (o poder elegir versions)
3_ Que herramientas usar para validar los yaml?.

Saludos.

**Comment by pablokbs** [comment]
Ese comando sirve para hacer lo que hiciste, creo que está bien. La verdad no conozco una mejor forma de hacer lo que hiciste, yo lo que hago es ver la documentación y lo cambio a mano. Para validad yaml yo uso el mismo validador de yaml en Sublime3. Nada especial.

Podrias hacer un PR cambiando esos archivos que ya están deprecados?

**Comment by rodrigo398** [comment]
Creo que ya podemos cerrar este issue.
