### ISSUE TITLE
Raspberry pi 3 + OMV4 + Docker raspbian/Desktop

### ISSUE THREAD

**Issue by ivanqj** [pablokbs/peladonerd#63]
Hola amigos soy nuevo en este fantástico  mundillo, no sé si lo que les voy a comentar se puede hacer con una única Raspberry Pi. Tengo la Raspberry Pi con el OMV4 ( cargue una imagen del OMV4 directamente en la tarjeta SD de la Raspberry) y lo tengo como Nass , tanto por FTP como samba. Mi duda es la siguiente, hay alguna forma de instalar en la Raspberry Pi un docker de sistema operativo tipo raspbian/Desktop y acceder vía web al sistema operativo?? Gracias ante todo

**Comment by pablokbs** [comment]
Hola, metete al slack y lo vemos ahi: slack.peladonerd.com

Pero me parece que tenés un par de conceptos erróneos: la idea de docker no es correr un sistema operativo entero, sino solo un proceso (que vive dentro de un directorio con todos los archivos necesarios, incluidos el sistema operativo) ... o sea, lo que vos queres hacer es levantar un SO entero dentro de docker, eso es posible pero no tiene mucho sentido.

Te conviene instalar una VM.
