### ISSUE TITLE
Poste.io siempre SPAM

### ISSUE THREAD

**Issue by cmastro** [pablokbs/peladonerd#7]
Hola Pablo! Te jodo devuelta con algunos problemas que me han surgido.

He seguido los pasos para instalar el servidor de correo Poste.io, lo cual esta genial!! Pero.. lamentablemente hay un pero, sino no estaría jodiendo.. absolutamente todos los correos que envío desde la cualquier cuenta creada llegan como Spam y algunos ni siquiera salen del servidor obteniendo el mensaje "Delivery Status Notification (Failure)" casi instantáneamente.

Cuando envío un correo a una cuenta GSuit es cuando llega rebotado con el siguiente mensaje: "The response was:
Your email to group @dominio was rejected due to spam classification. The owner of the group can choose to enable message moderation instead of bouncing these emails. More information can be found here: https://support.google.com/a/answer/168383."

Y cuando envío a correos @gmail o @hotmail o @dominio (que por ejemplo tiene un postfix instalado" llegan como Spam absolutamente todos los correos.

Para aclarar un poco, al ver el correo original obtengo lo siguiente:
SPF:	PASS
DKIM:'PASS' 
Received: from localhost (mail [127.0.0.1]) by mail.dominio.com (Haraka) with ESMTPSA id F3B6DKA1-AB00-4CA9-A230-3753F532382F.1 envelope-from <prueba@dominio.com> (authenticated bits=0) (version=TLSv1/SSLv3 cipher=ECDHE-RSA-AES128-GCM-SHA256 verify=FAIL); 

NOTA: dominio.com es un dominio de ejemplo, pero el que utilizo existe obviamente! 

Para este FAIL, intente cambiar el archivo HOST tanto del Droplet como del Docker, pero solo cambia de "localhost (mail [127.0.0.1])" a "localhost (ip6-localhost [::1])" y alguna otra forma, pero en ningun caso logro que lleguen los correos sin ser detectados como SPAM.

Cualquier ayuda se agradecerá!!
Muchas gracias!!!!
Saludos!!

**Comment by pablokbs** [comment]
Buenas, el tema de spam con los servers de correos es todo un tema, por empezar te recomiendo que visites este sitio `https://mxtoolbox.com/domain/dominio.com/` ... ahi te va a tirar tips de cosas que tal vez te estan faltando y capaz te da una idea por donde empezar, lamentablemente sin saber tu dominio no puedo debuggear, si querés postea tu dominio y después editá el comentario sacandolo, a mi me va a llegar el mail de github con los 2 comentarios y voy a poder probarlo.

**Comment by cmastro** [comment]
Estoy haciendo pruebas para poder implementarlo en un server de correos que ya se encuentra en produccion. Este dominio es solo de prueba.. asi que te paso un acceso al panel por si te sirve de algo. No se si te pueda dar o te sirva un acceso al Droplet de DigitalOcean?

https://mail.cofactura.com/admin
U: pablokbs
P: EjXKJuLhpW

PD: Como veras, te estoy siguiendo los pasos en tus tutos jaja!! 
Muchas gracias por tu ayuda!

**Comment by cmastro** [comment]
Buenas nuevamente.. ahi te mande unos datos.. pero no se si te han llegado :P 

Gracias nuevamente!!!

**Comment by pablokbs** [comment]
Probá agregando estas 2 lineas a tu servicio de poste en el `docker-compose.yaml`:

```
  hostname: mail
  domainname: dominio.com
```

Y probá de nuevo después de hacer un `docker-compose up -d`

**Comment by cmastro** [comment]
Lamentablemente sigue llegando como spam o rebotando dependiendo del receptor.. y lo peor es que debe ser una boludes que se me está pasando...

Así tengo el archivo "docker-compose.yaml"

`
version: "3.4"

services:
  poste:
    image: analogic/poste.io
    restart: always
    network_mode: "host"
    expose:
      - 25
      - 80
      - 443
      - 110
      - 143
      - 465
      - 587
      - 993
      - 995
    volumes:
      - /root/mail-data:/data
    environment:
      - HTTPS=ON
    hostname: mail
    domainname: dominio.com`

**Comment by pablokbs** [comment]
Mismo error ?

**Comment by cmastro** [comment]
si si.. mismo error.. este es el "mensaje original" que recibo:

> Delivered-To: cmastro84@gmail.com
Received: by 2002:ac9:128e:0:0:0:0:0 with SMTP id w14csp6211378ocb;
        Sun, 26 May 2019 12:23:54 -0700 (PDT)
X-Google-Smtp-Source: APXvYqxQoKLtwc0APlrM5XBVrLEvDmYpqtnFu0G5aOIOe2hAKGFJP2ovK5dklyMyuXjfMEJc4wiT
X-Received: by 2002:a1f:b70c:: with SMTP id h12mr15775138vkf.76.1558898634327;
        Sun, 26 May 2019 12:23:54 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1558898634; cv=none;
        d=google.com; s=arc-20160816;
        b=KBjVS3af2cQkegH7D7rv5b4AhlEck1OUja5+Y1GCwFu2RKD4cbE5nr7QNnOEvIQ2qH
         IuKD41d8/1kqZbQ3UuTlM/VxZCy4nL01drL1TZeSsrI22eUXQd5zBv/KwtfQFAX7p3Dl
         K74tmZfIvvJH2mIzvjOdvUxQtZGpgX5f8ZiWNqY8VMF4zf5q+ZIhhyzs4xesX/6CZGjV
         UPyDXtdvw/0qFl8skR7l3Y25+U+17lEAO7Gv/3djY3pPRGD9txv2jup6SmlLQ9bF9rz6
         WKxcQWm/PcupQzXqHxvYx9XJVoe7z+XSqldC/bdaFCY400XICVEe1lse7ztif/L0ypd0
         IBJw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=dkim-signature:user-agent:message-id:disposition-notification-to
         :return-receipt-to:subject:to:from:date:content-transfer-encoding
         :mime-version;
        bh=QD2/liO8C7GtaGrlZ1Lbsjhvk4eHe7jqZUtkt/kGXgI=;
        b=zlXYI7hhESftQMF+E8xeDXWhsHN0ty/4fuRngkVY2S2lXLZHW3n2st6AOOlOGlkDJU
         uu0zyqdXy7b5lNOhJmOlsyoZGX1P9c2cM53tHTpejVYZg5kwaZzmLs74jnMaj9jXCxDE
         NoVFrEvJRJRZaCg50lNKzWxqVSKTC6nUvOYwxJfN8WAsBvvXHJ0c0j1OkkzhHtd/0Z5r
         TmbEVxGUsA3fmt8r3dltlpCv0FGOTdKgZB3b3VRln2HR8SZDntKVzhEW/GhaZY/qq9Rb
         4vNmFvwk57NgBVSMSV66F7kkeMrzDm+rj5Aa9aJAOzFSHAadkx42RJ5zn7mepVkFSn1e
         y47Q==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@cofactura.com header.s=s20190513224 header.b=hIkAtwQw;
       spf=pass (google.com: domain of admin@cofactura.com designates 198.199.90.13 as permitted sender) smtp.mailfrom=admin@cofactura.com
Return-Path: <admin@cofactura.com>
Received: from mail.cofactura.com (mail.cofactura.com. [198.199.90.13])
        by mx.google.com with ESMTPS id u22si3167356vsp.51.2019.05.26.12.23.54
        for <cmastro84@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256/256);
        Sun, 26 May 2019 12:23:54 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin@cofactura.com designates 198.199.90.13 as permitted sender) client-ip=198.199.90.13;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@cofactura.com header.s=s20190513224 header.b=hIkAtwQw;
       spf=pass (google.com: domain of admin@cofactura.com designates 198.199.90.13 as permitted sender) smtp.mailfrom=admin@cofactura.com
Authentication-Results: mail.cofactura.com; auth=pass (login)
Received: from localhost (mail [::1]) by mail.cofactura.com (Haraka) with ESMTPSA id D6428B05-413D-468D-BD18-9D324444E061.1 envelope-from <admin@cofactura.com> (authenticated bits=0) (version=TLSv1/SSLv3 cipher=ECDHE-RSA-AES128-GCM-SHA256 verify=FAIL); Sun, 26 May 2019 19:23:53 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII; format=flowed
Content-Transfer-Encoding: 7bit
Date: Sun, 26 May 2019 16:23:52 -0300
From: admin@cofactura.com
To: cmastro84@gmail.com
Subject: prueba
Return-Receipt-To: admin@cofactura.com
Disposition-Notification-To: admin@cofactura.com
Message-ID: <48806a306f9e9b8c22f57b298ab3cbe5@cofactura.com>
X-Sender: admin@cofactura.com
User-Agent: Roundcube Webmail/1.3.8
DKIM-Signature: v=1;a=rsa-sha256;bh=QD2/liO8C7GtaGrlZ1Lbsjhvk4eHe7jqZUtkt/kGXgI=;c=relaxed/simple;d=cofactura.com;h=from:subject:date:message-id:to:mime-version;s=s20190513224;b=hIkAtwQwBaoJ+foTPiER0fnnb8OiAsYJSQwlXp2yPsb3U2rvs0b6xoUm8gan4/pQiyrvey7uV02paIBtNyWvurHMQle0C2/po30iHLs+WCPd38Cp6GgPweGtAEcIVUqgCENbHm7r7G4rW9udnf6slXEBl0GTuyJoj52WDzQk27m1o0tb5/ERF975TTinsVF8JPq4tYBz9CL47i644VYvRlPnkApBvZ3B6q7xRDPgLafeTXS0DsBH3m/JFH0PCUv6XpJQyZ2cvTv76wFIXUB5D2LKvDNtZr/GqDsvvgLk5P214kJ+H3heUxgnK3F4lll0IZHfcmxlvVQ+fH/rsWDHYg==

esto es una prueba

**Comment by cmastro** [comment]
Lo que no me "gusta" del "correo original" que te mande.. pero no se si vendrá por ahi la mano.. es: 

> Received: from localhost (mail [::1]) by mail.dominio.com (Haraka) with ESMTPSA id sdfsdf-adsf-468D-BD18-afasf envelope-from <admin@dominio.com> (authenticated bits=0) (version=TLSv1/SSLv3 cipher=ECDHE-RSA-AES128-GCM-SHA256 verify=FAIL);

**Comment by pablokbs** [comment]
Habria que buscar un poco mas de info acerca de ese error de verificación, voy a darle una mirada de nuevo en estos dias, pero no prometo nada

**Comment by fradducho** [comment]
Me funciona casi todo 99%.

Cuando envío correos los recibe el destinatario al vuelo. Pero cuando el destinatario responde el correo nunca llega :) ni esperando varios minutos. ni en spam ni en ningún lado. Le ha pasado eso ?

 Muchas Gracias

**Comment by pablokbs** [comment]
> Me funciona casi todo 99%.
> 
> Cuando envío correos los recibe el destinatario al vuelo. Pero cuando el destinatario responde el correo nunca llega :) ni esperando varios minutos. ni en spam ni en ningún lado. Le ha pasado eso ?
> 
> Muchas Gracias

No me ha pasado, habria que ver si sale algo en los logs de poste

**Comment by DylanPozuelo93** [comment]
Me pasa exactamente lo mismo que a el primer comentario de **cmastro**; configuro records SPF, DMARC y DKIM (con  la llave generada desde admin/virtual domains) en el dominio, configuro la droplet y corro la imagen de analogic/poste.io tal y como se recomienda, pero a la hora de enviar correos, todos llegan directo a la carpeta SPAM del receptor. Sería muy bueno un tutorial con tips para buenas practicas de configuración del servidor de correos con Poste.io (o similar), y como evitar que nuestros correos, con este sistema, lleguen directo a la carpeta SPAM de los receptores.
Estimado **PabloKBS** le solicito humildemente que nos ayude con un video sobre este tema, que actualmente es muy útil para las pequeñas empresas que surgen (como es mi caso).

**Comment by pablomenino** [comment]
@DylanPozuelo93, probaste revisar la configuración de los registros SPF, DMARC y DKIM desde algún servicio en la web?, la tool del mismo poste te da info de eso. Me pasaba lo mismo con GMail porque no tenia bien configurado el registro SFP.

La otra es ver si la IP que tenes (dirección IP para SMTP) no este en algún listado de Spam Abuse.

También me rebotaban los mail cuando enviaba a dominios donde revisan los registros PTR, que seria la inversa del DNS, revisan que la IP del SMTP este dentro de la zona de reversos para el dominio. que exista algo asi en el dns: 4.3.2.1.in-addr.arpa. IN PTR server.example.com

Como en mi caso al tener un Cable Modem, no tengo una IP fija asignada, tuve que optar por enviar mails usando un SMTP Relay, de esta forma el mail se enviá usando la dirección IP de quien te da el servicio y te garantiza el envió (siempre y cuando configures bien los registros DKIM y SFP).

Poste te permite configurar un SMTP externo en "Default SMTP route"

Hay varias empresas que ofrecen el servicio gratis para una cantidad x de mail por mes. De todas formas no suele ser muy caro para una empresa que no tiene un servicio de internet dedicado.

**Comment by pablokbs** [comment]
Voy a armar un videito para poder resolver estos problemas, como dice @pablomenino la mejor es usar un smtp externo, yo estoy usando sendgrid.net, es gratis y permite enviar varios miles de mails por mes, es mas que suficiente para algo personal o una empresa chica

**Comment by luisgagocasas** [comment]
Otro buen servicio smtp externo que e probado y funciona bien es sendinblue.com te da 300 envíos de correo por día gratis.

**Comment by pablokbs** [comment]
Cierro, al final hice un video de sendgrid que pueden ver [aca](https://www.youtube.com/watch?v=hhF9JExJFDc)

**Comment by rubenrafaelmercado** [comment]
Hola @pablokbs y a todos. Gracias por el valioso aporte. Les dejo mis tips.
https://github.com/pablokbs/peladonerd/issues/53#issuecomment-859063641

**Comment by crisswalt** [comment]
Hola a todos, no sé si llego en buen momento. Yo instalé poste.io en AWS hace unos días (12/05/2022). Como muchos tuve el problema de que los correos enviados llegaran a spam. Sin embargo después de investigar y solucionarlo, hago el siguiente resumen (espero les sirva):

1. Instalación de poste.io en nueva instancia ec2
2. Se agrega IP elástica a la misma instancia
3. Se crea el registro DNS "A" con un nombre de dominio para el servidor
4. Se crea el registro DNS "TXT" para el "SPF"
5. Se instala poste.io desde el nuevo nombre de dominio asociando dicho nombre a la aplicación.
6. Se genera el certificado SSL letsencrypt
7. Se genera el DKIM en el dominio virtual en poste.io
8. Se crea el registro DNS "TXT" del DKIM para el dominio
9. Se genera o crea el registro DNS INVERSO. En AWS se usa el administrador de IP elástica para ello. En en el caso de AWS, éste último genera por detrás un registro PTR para la IP que lo asocia al dominio principal de envío de correos. 

Para saber más al respecto, recomiendo este link https://www.hostinger.es/tutoriales/ptr-record

**Comment by pipounix** [comment]
si no tienes  mucho volumen de correo y manejas  solo un dominio  podes usar  algunos de  los relay smtp  gratuitos  brevo por ejemplo te deja enviar 100 mails por dia para un solo dominio   es facil configurarlo  en  posteio desde dentro del panel   todo el trafico de salida pasara por ahi  y  te olvidas  del ptr  dkim solo aplicas politica dmarc  y el spf  designado por   brevo   sendgrid  es otro que si tienes un volumen bajo de envios  se puede configurar   para saber bien el estado del servidor  puedes usar mxtoolbox y mail-tester para ver como salen tus envios  si llegan a spam en gmail  puede  ver el original  y analizar  la falla  y si la ip del servidor que suele ser lo comun esta en alguna blacklist  mxtoolbox te va a informar   y ver como la pasas  a  whitelist  en los DNSBL
