### ISSUE TITLE
en el video prometheus con grafana ejecuto el -k que haces pero me sale este error

### ISSUE THREAD

**Issue by boya678** [pablokbs/peladonerd#70]
unable to recognize ".": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

me das una mano?

**Comment by pablokbs** [comment]
metete al slack y lo vemos ahi slack.peladonerd.com (va a ser mas rapido que por acá)
