### ISSUE TITLE
Consulta en armado de docker_compose.yml personal

### ISSUE THREAD

**Issue by LuisZambranaBlog** [pablokbs/peladonerd#83]
Hola pelado te escribo para ver si me podes ayudar en la configuracion de mi docker_compose.yml el cual te paso a continuacion. **Todo anda bien, menos el mailserver que es lo que quisiera que veas, desde ya MUCHAS GRACIAS!!!!!!:**

`version: '3.7'

services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dbmysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: base
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  wplz:
    depends_on:
      - db
    image: wordpress:latest
    expose:
      - "80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: base
      VIRTUAL_HOST: midominio.com.ar
      LETSENCRYPT_HOST: midominio.com.ar
      LETSENCRYPT_EMAIL: mail@mail.com
    volumes:
      - ./wordpress:/var/www/html
      
  db1:
    image: mysql:5.7
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dbmysql1:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: base
      MYSQL_USER: user
      MYSQL_PASSWORD:  pass

  wpMA:
    depends_on:
      - db1
    image: wordpress:latest
    expose:
      - "80"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: base
      VIRTUAL_HOST: midominio2.com.ar
      LETSENCRYPT_HOST: midominio2.com.ar
      LETSENCRYPT_EMAIL: mail@mail.com
    volumes:
      - ./wordpressMA:/var/www/html

  jwilder-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      DEFAULT_HOST: midominio.com.ar
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=jwilder-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    depends_on: 
      - "jwilder-proxy"

mailserver:
    image: analogic/poste.io
    container_name: mailserver
    restart: unless-stopped
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - LETSENCRYPT_EMAIL=mail@mail.com
      - LETSENCRYPT_HOST=mail.midominio.com.ar
      - HTTPS=ON
      - DISABLE_CLAMAV:TRUE 
      - VIRTUAL_HOST: mail.midominio.com.ar
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/nginx/html/.well-known:/opt/www/.well-known
      - /data/mailserver:/data
      - vhostd:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:rw
 
volumes:
  certs:
  vhostd:
  html:`

**Comment by pablokbs** [comment]
A que te referis con que anda mal? Poné los errores que veas

**Comment by LuisZambranaBlog** [comment]
> A que te referis con que anda mal? Poné los errores que veas

Gracias pablokbs por contestar... pense que no levantaba el docker y si lo hacia bien!
al ver el log me dice que entre a la ip por https para configurar o sea que esta todo andando.
Si ves yo ya tengo un dominio.com con https de letencryp y al poner https://mail.midominio.com.ar no puedo acceder al panel de configuracion de poste.... sera que tengo que crear en digital ocean el "mail".... se me complico con eso pero la verdad esta funcionando solo no puedo acceder por algo de config
gracias por la ayuda!

**Comment by pablokbs** [comment]
> no puedo acceder al panel de configuracion de poste

A que te referis con esto? podes poner el error que ves?

**Comment by LuisZambranaBlog** [comment]
> > no puedo acceder al panel de configuracion de poste
> 
> A que te referis con esto? podes poner el error que ves?

Voy a explicar mejor esta vez:
La verdad no tenia mucha idea de poste entonces copie parte de tu proyecto. y lo subi al mio.
Cuando ejecute el docker-compuse up -d funciono todo (respondieron done done done)...
Luego no podria ingresar a la configuracion. Fui arreglando todo hasta que me quedo asi:
mailserver:
    image: analogic/poste.io
    container_name: mailserver
    hostname: mail.midominio.com.ar
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      TZ: America/Argentina/Buenos_Aires
      LETSENCRYPT_EMAIL: mail@mail.com
      LETSENCRYPT_HOST: mail.midominio.com.ar
      DISABLE_CLAMAV: "TRUE"
      VIRTUAL_HOST: mail.midominio.com.ar
      HTTPS: "OFF"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/nginx/html/.well-known:/opt/www/.well-known
      - ./data/mailserver:/data
      - vhostd:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:rw
En difital ocean cree los dns que indican en la config y ya pude crear cuentas recibir correos pero no puedo enviar. No da error, simplmente dice correo enviado y nada...
Que podria ser?? gracias !!! y disculpas

**Comment by pablokbs** [comment]
Ok bien ahora si. En digital ocean por defecto te bloquean la salida a los mails, creo que si mandas un ticket de soporte a veces te lo desbloquean, pero asi y todo vas a tener problemas porque casi siempre los servers de ellos están en listas negras por lo que van a llegar a spam.

Mi recomendación es que uses sendgrid con poste, hice un video de esto [acá](https://www.youtube.com/watch?v=hhF9JExJFDc). Probalo y cualquier cosa volvés a abrir el issue

Saludos
