### ISSUE TITLE
¿Puedo separar las carpetas "www" en otro docker-compose y tenarlas independientes?

### ISSUE THREAD

**Issue by tho7o** [pablokbs/peladonerd#86]
Pablo,

Todo funciona perfecto, pero quisiera hacer lo siguiente editando tu docker-compose.yml (dc.yml):
_Tengo una carpeta llamada "PROXY":_

**PROXY:**
1. docker-compose.yml (nginx + letsencrypt) 

_dentro de esta carpeta, están las siguientes carpetas:_

**PROXY/WEB1:**
1. dc.yml para una web 1 [web1.com]
2. README.md

**PROXY/WEB2:**
1. dc.yml para web 2 [web2.com]
2. mysql/
3. html/
2. README.md

La idea es que el contenedor de ngnx+letscrypt **("PROXY")** sea independiente de las aplicaciones que monte posteriormente en las subcarpetas con otro docker-compose y que siga redirigiendo tal como lo hacía tu docker-compose hacia las subcarpetas www.

Ya he montado todos los contenedores en la misma red que genera el docker **PROXY**, pero cuando monto los 3 contenedores **(PROXY + WEB1 +WEB2)** e intento navegar a "web1.com", el navegador no encuentra el **index.html** de la carpeta de **PROXY/WEB1**. Me da un "**403 forbidden**".

¿Me podrías dar algún tip?

Gracias,

**Comment by pablokbs** [comment]
Habría que ver el log del nginx-proxy para ver por que muestra ese 403, si está todo en la misma red y pusiste las variables de entorno (`VIRTUAL_HOST`) deberia andar

**Comment by tho7o** [comment]
He resuelto Pablo. Tema de rutas relativas. Cualquier persona que esté interesada, con gusto comparto.
