### ISSUE TITLE
no llega los mails poste.io

### ISSUE THREAD

**Issue by asuajegilberto** [pablokbs/peladonerd#88]
hola estuve usando la receta y envia los mails y configure https sin embargo no me llegan los msj pero tampoco los rebota mi gmail

**Comment by pablokbs** [comment]
es muy probable que tus mails no se manden porque tengas el puerto bloqueado, fijate en la administración de poste, en "Delivery queue" deberian aparecer

**Comment by asuajegilberto** [comment]
no, nunca me llego el "delivery queue" solo no entraban despues de mucho leer y muhco probar me hacia falta un domain de tipo MX y en lo que estuvo la propagación lista comenzaron a llegar todos los anterior enviados. muchas gracias..! saludos
