### ISSUE TITLE
poste.io sirve para entornos corporativos?

### ISSUE THREAD

**Issue by catrielmercurio** [pablokbs/peladonerd#90]
Hola pelado! Hace tiempo que vengo viendo alguna posibilidad para montar en aws algun servidor de correo, ya que en mi empresa estamos usando un viejo mdaemon en win server y el portal que usamos para trabajar todo el dia envia correos.... el video que hiciste de poste.io en un minuto me parecio muy copado ¿pensas que es una solucion viable para un entorno corporativo? o deberia descartarlo?

Gracias por todo lo enseñado!

**Comment by pablokbs** [comment]
Buenas, depende a que te refieras con corporativo, para mi corporativo es una empresa con mas de 1000 empleados, en ese caso, me parece que poste es algo muy chico. En mi caso, yo lo he instalado en un pequeño ISP (menos de 100 usuarios) y anda bien. No se si lo recomendaría para algo muy grande, tal vez en ese caso necesitarías algo mas poderoso como Zimbra o sino ir directo a Gmail.

Si ya estas usando un server de correo instalado a mano, poste es una buena opción, es facil de manejar y anda bien

**Comment by catrielmercurio** [comment]
Graicas por la respuesta!! Voy a probarlo... Es mas que nada por los envíos que hace el portal!! Pero voy a probarlo para sacarme las ganas, porque realmente me parecio muy simple!

Saludos!
