### ISSUE TITLE
headers en ingress con nginx-ingress-controller

### ISSUE THREAD

**Issue by epenia** [pablokbs/peladonerd#91]
Buenas, tengo un balanceador en google cloud platform que me hace de terminador de SSL, este cuando acceden por SSL introduce estos headers X-Forwarded-Proto y X-Forwarded-Port, alguno sabe como puedo hacer para nginx-ingress pase esos headers al pod?

Gracias.

**Comment by pablokbs** [comment]
Hola, en la [doc de nginx ingress](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers) dice que deberias pasar la opción `use-forwarded-headers: true` al configmap de ingress.

Fijate con eso, saludos

**Comment by epenia** [comment]
Buenas @pablokbs ,

Por lo que estoy viendo hay 2 nginx-controller el oficial de kubernetes y otro de nginx

- https://kubernetes.github.io/ingress-nginx/deploy/#bare-metal 
- https://docs.nginx.com/nginx-controller/v3/install-nginx-controller/ (yo estoy usando este)

En el nginx ingress que estoy usando yo no veo esa opción.

Gracias de antemano.
