### ISSUE TITLE
Jitsi Meet

### ISSUE THREAD

**Issue by fjbardelli** [pablokbs/peladonerd#94]
Levante Jitsi atrás de un traefik 2, don el ejemplo que está en el repo de jitsi, para usar Traefik.
Anda bien pero se desconecta y re conecta todo el tiempo. El server no se cae, pero las salas que abro se re conectan todo el tiempo 
Alguien le paso algo parecido?

**Comment by pablokbs** [comment]
Vas a tener que pasar toda tu config con los logs para que podamos ayudarte. Probaste preguntar en el repo de jitsi?

**Comment by fjbardelli** [comment]
Ahora armo la info si hay un par de cosas con una clave del env de configuración pero no me funcionó
