### ISSUE TITLE
seguridad de carpetas en el servidor

### ISSUE THREAD

**Issue by XaviLavigne** [pablokbs/peladonerd#96]
hola buenas tardes!!!!
soy nuevo en docker, apenas llevo un par de días y buscando en tus videos no pude encontrar una solución a mi problema..... 
Terminé una aplicación que usarán varias clínicas (independiente una de otra) donde tomaran
 imágenes de los equipos médicos y generará el diagnostico individual del paciente.
El problema está en que cada clínica tendrá su propio servidor privado y usaré docker para montar el servidor  directamente desde la imagen. Pero como evito que una persona X entre a ese servidor, y desde la terminal copie los archivos de /html/ a un pendrive por ejemplo. Ya que en esa carpeta no solo estará el código fuente del sistema, sino también la base de datosde los pacientes, imágenes médicas, e historial clínico. 

Espero puedan ayudarme Gracias.

**Comment by fabdelgado** [comment]
Hola @XaviLavigne, no podes cambiar la implementación?, lo mejor me parece en estos casos sería que sea guardado en un storage que la aplicación haga push y no en el servidor mismo de esa manera podrías tener la seguridad que si un día se rompe algo tendrías un backup de esos files y manejarlos seguros en un storage gestionado externamente, algo así como S3.

**Comment by XaviLavigne** [comment]
El problema está en que las máquinas no estarán conectadas a Internet, es un  protocolo que implementaron. así que se tiene que guardar forzosamente en el servidor, y pensé usar docker para proteger la ibfo 😥

**Comment by fabdelgado** [comment]
Y no podrías guardar las imágenes en la base de datos en base 64?, la otra idea es encriptar los archivos no se que framework o lenguaje estas usando pero en laravel existe esto https://medium.com/better-programming/how-to-encrypt-large-files-in-laravel-293460836ded

**Comment by XaviLavigne** [comment]
me olvide comentarlo, estoy usando php y ya probé guardando las imágenes directo en la base de datos, el problema está en que las imágenes son muy grandes y se realizan alrededor de 20 tomas por paciente y son alrededor de 150 pacientes día... y eso influye bastante en la velocidad del servidor pasado unos dias😥. investigaré Laravel! muchas gracias

**Comment by fabdelgado** [comment]
Y la otra alternativa que te pase de encriptar y desencriptar?

**Comment by PabloScolpino** [comment]
Hola.
Me parece que tenes que definir bien el "modelo de ataque". Si alguien tiene acceso fisico al server y no deberia, en general ya estas en problemas.

Asumiendo que quienes tengan acceso al server no tengan acceso de administrador, podes usar *[acl](https://en.wikipedia.org/wiki/Access-control_list)* para limitar el acceso a los directorios. (esto se puede en windows y todo lo *nix).
---------

1. usa `docker-compose` para estructurar la aplicacion y definir bien las rutas a usar y que todo quede en un solo archivo
2. usa `ansible` para automatizar la configuracion de los servers
3. usa *acl* para establecer los accesos a los directorios que definiste en 1. donde solo la aplicacion y los usuarios que correspondan puedan acceder al codigo y los datos (datos, imagenes, db, etc).
4. despues de haber configurado todo, hace una instalacion en una maquina de prueba e intentar entrar de varias formas, con ganas.
5. te recomiendo que uses una computadora independiente de las terminales para hostear la aplicacion. aunque no sea ultimo modelo es preferible a que la comparta con un usuario para que la confiabilidad / estabilidad del sistema sea mayor.
6. si existe un equipo de sistemas en los establecimientos donde se va a instalar, podes preguntar/pedir almacenamiento de red y almacenar las imagenes ahi. Eso te permitiria delegar la proteccion del material sensible en un 3ro, en algunos casos eso es buena idea si tenes pocos recursos (de tiempo, almacenamiento, etc).

---------

Usar imagenes en las bases de datos *NO* es una buena idea. Usa file storage nativo de la plataforma, que para eso es *FILE-STORAGE* :-).

---------
Lo que dijo @fabdelgado de "encription-at-rest" es una idea interesante, pero no es trivial de configurar.
Si estas arrancando yo te sugiero que primero que nada _documentes cual es el escenario de ataque del que te queres protejer_ (por ejemplo, usuario standard de la oficina/clinica que comparte acceso a la terminal (en el caso que el server sea server y terminal a la vez) no tiene que poder navegar a la carpeta de imagenes y descargarlas, etc, etc). Una vez tengas bien en claro cuales son los escenarios de los que te vas a protejer, ahi busca las herramientas.

**Comment by XaviLavigne** [comment]
muchas gracias, ahora mismo me pongo a investigar y probar las opciónes que me mencionaste, y lastimosamente el problema de darme una sola maquina como servidor y terminal a la vez es una limitación que me impusieron 😥.

**Comment by PabloScolpino** [comment]
Si no te dan hosting independiente, vas a tener que configurar los permisos con ACL. 
Todo esta charla me hace suponer que va a estar hosteado en la computadora corriendo windows de alguien de la oficina. Si la persona que usa la computadora tiene permisos de administrador del sistema, ACL te protejera solo parcialmente.
Nuevamente, si alguien tiene acceso físico al equipo, lo que vos podes hacer realísticamente con software para proteger los datos es relativamente poco.
Yo les haría firmar un documento donde te desligues de la responsabilidad de la custodia de los archivos. Ahorran costo de hosting, pero hay costos de responsabilidad que no te corresponde absorber (reitero, la protección que podes razonablemente implementar en software no cubre todos los vectores de ataque (por ejemplo, reinicio la computadora con un pendrive, booteo en linux, monto el directorio y me copio lo que se me canta sin prestarle atención ni siquiera al ACL).
